CREATE OR REPLACE VIEW V_PARITE AS
    SELECT
        P.DEVISEEURO,
        P.DEVISEDOLLAR,
        P.VALEUR,
        EXTRACT(MONTH FROM P.DATEPARITE) AS MOIS,
        EXTRACT(YEAR FROM P.DATEPARITE)  AS ANNEE
    FROM
        PARITE P;

CREATE OR REPLACE VIEW V_RACK_CELLULE AS
    SELECT
        C.ID                      AS IDCELLULE,
        R.DESIGNATION
        || ''
        || C.DESIGNATION          AS DESIGNATION,
        R.IDSECTIONWMS,
        S.SECTION,
        R.ID                      AS IDRACK,
        R.DESIGNATION             AS DES_RACK,
        R.IDCATEGORIETISSU,
        CT.CATEGORIE              AS CAT_TISSU,
        C.DESIGNATION             AS DES_CELLULE,
        C.IDCLASSEMATIEREPREMIERE,
        CMP.CLASSE
    FROM
        CELLULE               C
        JOIN RACK R
        ON C.IDRACK = R.ID
        JOIN SECTIONWMS S
        ON R.IDSECTIONWMS = S.ID
        JOIN CATEGORIETISSUS CT
        ON R.IDCATEGORIETISSU=CT.ID
        JOIN CLASSEMATIEREPREMIERE CMP
        ON C.IDCLASSEMATIEREPREMIERE=CMP.ID
    WHERE
        C.ETAT=0;

CREATE OR REPLACE VIEW V_ENTREE_TISSU AS
    SELECT
        E.DATEENTREE,
        E.DATEFACTURATION,
        E.IDCATEGORIETISSUS,
        CT.CATEGORIE,
        E.IDCLASSEMATIEREPREMIERE,
        CMP.CLASSE,
        E.IDUTILISATIONWMS,
        UW.UTILISATION,
        E.IDDONNEBC,
        E.NUMEROBC,
        E.NUMEROBL,
        E.NUMEROFACTURE,
        E.IDFOURNISSEUR,
        TF.NOMTIER                     AS FOURNISSEUR,
        E.IDCLIENT,
        TC.NOMTIER                     AS CLIENT,
        E.MODELE,
        E.SAISON,
        E.DESIGNATION                  AS DES_TISSU,
        E.REFTISSU,
        E.COMPOSITION,
        E.COULEUR,
        E.LAIZE,
        E.QTECOMMANDE,
        E.IDUNITEMESUREMATIEREPREMIERE,
        UMMP.UNITE_MESURE,
        E.QTERECU,
        E.TAUXECART,
        E.NBROULEAU,
        E.NBLOT,
        E.PRIXUNITAIRE,
        E.IDUNITEMONETAIRE,
        UM.UNITE                       AS UNITE_MONETAIRE,
        E.RESTERECEVOIR,
        E.FRET,
        E.COMMENTAIRE,
        E.IDFAMILLETISSUS,
        FT.FAMILLE_TISSUS,
        VP.VALEUR
    FROM
        ENTREETISSU                E
        JOIN CATEGORIETISSUS CT
        ON CT.ID= E.IDCATEGORIETISSUS
        JOIN CLASSEMATIEREPREMIERE CMP
        ON CMP.ID=E.IDCLASSEMATIEREPREMIERE
        JOIN UTILISATIONWMS UW
        ON UW.ID = E.IDUTILISATIONWMS
        JOIN DONNEBC DBC
        ON DBC.ID=E.IDDONNEBC
        JOIN UNITEMESUREMATIEREPREMIERE UMMP
        ON UMMP.ID=E.IDUNITEMESUREMATIEREPREMIERE
        JOIN UNITEMONETAIRE UM
        ON UM.ID = E.IDUNITEMONETAIRE
        JOIN FAMILLETISSUS FT
        ON FT.ID=E.IDFAMILLETISSUS
        LEFT JOIN V_PARITE VP
        ON VP.MOIS= EXTRACT(MONTH FROM E.DATEFACTURATION)
        AND VP.ANNEE=EXTRACT(YEAR FROM E.DATEFACTURATION)
        JOIN TIERS TF
        ON TF.ID=E.IDFOURNISSEUR
        JOIN TIERS TC
        ON TC.ID=E.IDCLIENT;

CREATE OR REPLACE VIEW V_SOMME_ENTREE_TISSU AS
    SELECT
        IDSTOCKTISSU,
        SUM(QTERECU) AS SOMMEQTERECU
    FROM
        ENTREETISSU
    GROUP BY
        IDSTOCKTISSU;

CREATE OR REPLACE VIEW V_SOMME_SORTIE_TISSU AS
    SELECT
        IDSTOCKTISSU,
        SUM(QTESORTIE) AS SOMMEQTESORTIE
    FROM
        SORTIETISSU
    GROUP BY
        IDSTOCKTISSU;

CREATE OR REPLACE VIEW V_STOCK_TISSU AS
    SELECT
        ST.*,
        CT.CATEGORIE,
        CMP.CLASSE,
        UW.UTILISATION,
        TF.NOMTIER          AS FOURNISSEUR,
        VSET.SOMMEQTERECU,
        VSST.SOMMEQTESORTIE
    FROM
        STOCKTISSU            ST
        JOIN CATEGORIETISSUS CT
        ON CT.ID= ST.IDCATEGORIETISSUS
        JOIN CLASSEMATIEREPREMIERE CMP
        ON CMP.ID=ST.IDCLASSEMATIEREPREMIERE
        JOIN UTILISATIONWMS UW
        ON UW.ID = ST.IDUTILISATIONWMS
        JOIN TIERS TF
        ON TF.ID=ST.IDFOURNISSEUR
        JOIN V_SOMME_ENTREE_TISSU VSET
        ON VSET.IDSTOCKTISSU=ST.ID
        LEFT JOIN V_SOMME_SORTIE_TISSU VSST
        ON VSST.IDSTOCKTISSU=ST.ID;

CREATE OR REPLACE VIEW V_SORTIE_TISSU AS
    SELECT
        ST.*,
        CT.CATEGORIE,
        CMP.CLASSE,
        UW.UTILISATION,
        TF.NOMTIER     AS FOURNISSEUR,
        TC.NOMTIER     AS CLIENT
    FROM
        SORTIETISSU           ST
        JOIN CATEGORIETISSUS CT
        ON CT.ID= ST.IDCATEGORIETISSUS
        JOIN CLASSEMATIEREPREMIERE CMP
        ON CMP.ID=ST.IDCLASSEMATIEREPREMIERE
        JOIN UTILISATIONWMS UW
        ON UW.ID = ST.IDUTILISATIONWMS
        JOIN TIERS TF
        ON TF.ID=ST.IDFOURNISSEUR
        JOIN TIERS TC
        ON TC.ID=ST.IDCLIENT;
