CREATE TABLE SECTIONWMS (
    ID SERIAL NOT NULL,
    SECTION VARCHAR(90) NOT NULL,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE CLASSEMATIEREPREMIERE (
    ID SERIAL NOT NULL,
    DESIGNATION VARCHAR(255) NOT NULL,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE RACK (
    ID SERIAL NOT NULL,
    IDSECTIONWMS INT4 NOT NULL,
    DESIGNATION VARCHAR(255) NOT NULL,
    LARGEUR NUMERIC(19, 5) NOT NULL,
    LONGUEUR NUMERIC(19, 5) NOT NULL,
    HAUTEUR NUMERIC(19, 5) NOT NULL,
    COMMENTAIRE VARCHAR(255),
    IDCATEGORIETISSU INT4 NOT NULL,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE CATEGORIETISSUS (
    ID SERIAL NOT NULL,
    CATEGORIE INT4 NOT NULL,
    ETAT INT4 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE CELLULE (
    ID SERIAL NOT NULL,
    DESIGNATION VARCHAR(255) NOT NULL,
    IDRACK INT4 NOT NULL,
    LARGEUR NUMERIC(19, 5) NOT NULL,
    LONGUEUR NUMERIC(19, 5) NOT NULL,
    HAUTEUR NUMERIC(19, 0) NOT NULL,
    IDCLASSEMATIEREPREMIERE INT4 NOT NULL,
    COMMENTAIRE VARCHAR(255),
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE PARITE (
    ID SERIAL NOT NULL,
    DATEPARITE DATE NOT NULL,
    DEVISEEURO NUMERIC(19, 5) NOT NULL,
    DEVISEDOLLAR NUMERIC(19, 5) NOT NULL,
    VALEUR NUMERIC(19, 5),
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE UTILISATIONWMS (
    ID SERIAL NOT NULL,
    UTILISATION VARCHAR(80) NOT NULL,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE UNITEMESUREMATIEREPREMIERE (
    ID SERIAL NOT NULL,
    UNITE_MESURE VARCHAR(25) NOT NULL,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE UNITEMONETAIRE (
    ID SERIAL NOT NULL,
    UNITE VARCHAR(25) NOT NULL,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE ENTREETISSU (
    ID SERIAL NOT NULL,
    IDFAMILLETISSUS INT4 NOT NULL,
    DATEENTREE DATE NOT NULL,
    DATEFACTURATION DATE NOT NULL,
    IDCATEGORIETISSUS INT4 NOT NULL,
    IDCLASSEMATIEREPREMIERE INT4 NOT NULL,
    IDUTILISATIONWMS INT4 NOT NULL,
    IDDONNEBC INT4 NOT NULL,
    NUMEROBC VARCHAR(90) NOT NULL,
    NUMEROBL VARCHAR(90) NOT NULL,
    NUMEROFACTURE VARCHAR(90) NOT NULL,
    IDFOURNISSEUR INT4 NOT NULL,
    IDCLIENT INT4 NOT NULL,
    MODELE VARCHAR(90) NOT NULL,
    SAISON VARCHAR(90) NOT NULL,
    DESIGNATION VARCHAR(255) NOT NULL,
    REFTISSU VARCHAR(255) NOT NULL,
    COMPOSITION VARCHAR(90) NOT NULL,
    COULEUR VARCHAR(90) NOT NULL,
    LAIZE NUMERIC(19, 4) NOT NULL,
    QTECOMMANDE NUMERIC(19, 4) NOT NULL,
    IDUNITEMESUREMATIEREPREMIERE INT4 NOT NULL,
    QTERECU NUMERIC(19, 4) NOT NULL,
    TAUXECART NUMERIC(19, 4) NOT NULL,
    NBROULEAU NUMERIC(19, 4) NOT NULL,
    NBLOT NUMERIC(19, 4) NOT NULL,
    PRIXUNITAIRE NUMERIC(19, 4) NOT NULL,
    IDUNITEMONETAIRE INT4 NOT NULL,
    RESTERECEVOIR NUMERIC(19, 4),
    FRET VARCHAR(200) NOT NULL,
    IMAGE TEXT,
    COMMENTAIRE TEXT,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE BCINTERNE (
    ID SERIAL NOT NULL,
    DATEBCINTERNE DATE NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE FAMILLETISSUS (
    ID INT4 NOT NULL,
    FAMILLE_TISSUS VARCHAR(255) NOT NULL,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE CELLULE_ENTREETISSU (
    IDENTREETISSU INT4 NOT NULL,
    IDCELLULE INT4 NOT NULL,
    PRIMARY KEY (IDENTREECT, IDCELLULE)
);

CREATE TABLE DONNEBC (
    ID INT4 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE TIERS (
    ID INT4 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE STOCKTISSU (
    ID SERIAL NOT NULL,
    IDCATEGORIETISSUS INT4 NOT NULL,
    IDCLASSEMATIEREPREMIERE INT4 NOT NULL,
    IDUTILISATIONWMS INT4 NOT NULL,
    REFERENCE VARCHAR(90) NOT NULL,
    DESIGNATION VARCHAR(90) NOT NULL,
    COMPOSITION VARCHAR(90) NOT NULL,
    COULEUR VARCHAR(90) NOT NULL,
    IDFOURNISSEUR INT4 NOT NULL,
    SAISON VARCHAR(90) NOT NULL,
    LAIZE NUMERIC(19, 4) NOT NULL,
    QTESTOCK INT4,
    UNITEMESUREMATIEREPREMIEREID INT4 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE STOCKTISSU_TIERS_MODELE (
    IDSTOCKTISSU INT4 NOT NULL,
    IDTIERS INT4 NOT NULL,
    MODELE VARCHAR(90) NOT NULL,
    PRIMARY KEY (IDSTOCKTISSU, IDTIERS)
);

CREATE TABLE PRIXUNITAIRESTOCKTISSU (
    ID INT4 NOT NULL,
    DATEPRIX DATE NOT NULL,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE RESERVATION (
    ID SERIAL NOT NULL,
    DATERESERVATION DATE NOT NULL,
    IDSTOCKTISSU INT4 NOT NULL,
    ETAT INT4 DEFAULT 0 NOT NULL,
    QTERESERVE NUMERIC(19, 4) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE CELLULE_STOCKTISSU (
    IDCELLULE INT4 NOT NULL,
    IDSTOCKTISSU INT4 NOT NULL,
    PRIMARY KEY (IDCELLULE, IDSTOCKTISSU)
);

ALTER TABLE RACK
    ADD CONSTRAINT FKRACK155234 FOREIGN KEY (
        IDSECTIONWMS
    )
        REFERENCES SECTIONWMS (
            ID
        );

ALTER TABLE RACK
    ADD CONSTRAINT FKRACK421903 FOREIGN KEY (
        IDCATEGORIETISSU
    )
        REFERENCES CATEGORIETISSUS (
            ID
        );

ALTER TABLE CELLULE
    ADD CONSTRAINT FKCELLULE350976 FOREIGN KEY (
        IDRACK
    )
        REFERENCES RACK (
            ID
        );

ALTER TABLE CELLULE
    ADD CONSTRAINT FKCELLULE471252 FOREIGN KEY (
        IDCLASSEMATIEREPREMIERE
    )
        REFERENCES CLASSEMATIEREPREMIERE (
            ID
        );

ALTER TABLE CELLULE_ENTREETISSU
    ADD CONSTRAINT FKCELLULE_EN448030 FOREIGN KEY (
        IDENTREECT
    )
        REFERENCES ENTREETISSU (
            ID
        );

ALTER TABLE CELLULE_ENTREETISSU
    ADD CONSTRAINT FKCELLULE_EN653622 FOREIGN KEY (
        IDCELLULE
    )
        REFERENCES CELLULE (
            ID
        );

ALTER TABLE ENTREETISSU
    ADD CONSTRAINT FKENTREETISS722881 FOREIGN KEY (
        IDCATEGORIETISSUS
    )
        REFERENCES CATEGORIETISSUS (
            ID
        );

ALTER TABLE ENTREETISSU
    ADD CONSTRAINT FKENTREETISS950787 FOREIGN KEY (
        IDCLASSEMATIEREPREMIERE
    )
        REFERENCES CLASSEMATIEREPREMIERE (
            ID
        );

ALTER TABLE ENTREETISSU
    ADD CONSTRAINT FKENTREETISS105006 FOREIGN KEY (
        IDUTILISATIONWMS
    )
        REFERENCES UTILISATIONWMS (
            ID
        );

ALTER TABLE ENTREETISSU
    ADD CONSTRAINT FKENTREETISS542858 FOREIGN KEY (
        IDDONNEBC
    )
        REFERENCES DONNEBC (
            ID
        );

ALTER TABLE ENTREETISSU
    ADD CONSTRAINT FKENTREETISS680585 FOREIGN KEY (
        IDUNITEMESUREMATIEREPREMIERE
    )
        REFERENCES UNITEMESUREMATIEREPREMIERE (
            ID
        );

ALTER TABLE ENTREETISSU
    ADD CONSTRAINT FKENTREETISS812293 FOREIGN KEY (
        IDFOURNISSEUR
    )
        REFERENCES TIERS (
            ID
        );

ALTER TABLE ENTREETISSU
    ADD CONSTRAINT FKENTREETISS696993 FOREIGN KEY (
        IDCLIENT
    )
        REFERENCES TIERS (
            ID
        );

ALTER TABLE ENTREETISSU
    ADD CONSTRAINT FKENTREETISS771884 FOREIGN KEY (
        IDFAMILLETISSUS
    )
        REFERENCES FAMILLETISSUS (
            ID
        );

ALTER TABLE ENTREETISSU
    ADD CONSTRAINT FKENTREETISS587915 FOREIGN KEY (
        IDUNITEMONETAIRE
    )
        REFERENCES UNITEMONETAIRE (
            ID
        );

ALTER TABLE STOCKTISSU
    ADD CONSTRAINT FKSTOCKTISSU39980 FOREIGN KEY (
        IDCATEGORIETISSUS
    )
        REFERENCES CATEGORIETISSUS (
            ID
        );

ALTER TABLE STOCKTISSU
    ADD CONSTRAINT FKSTOCKTISSU257941 FOREIGN KEY (
        IDCLASSEMATIEREPREMIERE
    )
        REFERENCES CLASSEMATIEREPREMIERE (
            ID
        );

ALTER TABLE STOCKTISSU
    ADD CONSTRAINT FKSTOCKTISSU657855 FOREIGN KEY (
        IDUTILISATIONWMS
    )
        REFERENCES UTILISATIONWMS (
            ID
        );

ALTER TABLE STOCKTISSU
    ADD CONSTRAINT FKSTOCKTISSU396435 FOREIGN KEY (
        IDFOURNISSEUR
    )
        REFERENCES TIERS (
            ID
        );

ALTER TABLE STOCKTISSU_TIERS_MODELE
    ADD CONSTRAINT FKSTOCKTISSU771176 FOREIGN KEY (
        IDSTOCKTISSU
    )
        REFERENCES STOCKTISSU (
            ID
        );

ALTER TABLE STOCKTISSU_TIERS_MODELE
    ADD CONSTRAINT FKSTOCKTISSU57871 FOREIGN KEY (
        IDTIERS
    )
        REFERENCES TIERS (
            ID
        );

ALTER TABLE STOCKTISSU
    ADD CONSTRAINT FKSTOCKTISSU923580 FOREIGN KEY (
        UNITEMESUREMATIEREPREMIEREID
    )
        REFERENCES UNITEMESUREMATIEREPREMIERE (
            ID
        );

ALTER TABLE RESERVATION
    ADD CONSTRAINT FKRESERVATIO801450 FOREIGN KEY (
        IDSTOCKTISSU
    )
        REFERENCES STOCKTISSU (
            ID
        );

ALTER TABLE CELLULE_STOCKTISSU
    ADD CONSTRAINT FKCELLULE_ST164699 FOREIGN KEY (
        IDCELLULE
    )
        REFERENCES CELLULE (
            ID
        );

ALTER TABLE CELLULE_STOCKTISSU
    ADD CONSTRAINT FKCELLULE_ST648322 FOREIGN KEY (
        IDSTOCKTISSU
    )
        REFERENCES STOCKTISSU (
            ID
        );

CREATE TABLE SORTIETISSU (
    ID SERIAL NOT NULL,
    NUMBCINTERNE VARCHAR(255) NOT NULL,
    FAMILLETISSUSID INT4 NOT NULL,
    QTESORTIE NUMERIC(19, 4) NOT NULL,
    DESIGNATION VARCHAR(90) NOT NULL,
    REFERENCE VARCHAR(90) NOT NULL,
    MODELE VARCHAR(90) NOT NULL,
    SAISON VARCHAR(90) NOT NULL,
    RECEVEUR VARCHAR(90) NOT NULL,
    LAIZE VARCHAR(200) NOT NULL,
    IDFOURNISSEUR INT4 NOT NULL,
    IDCLIENT INT4 NOT NULL,
    COMPOSITION VARCHAR(90) NOT NULL,
    DESTINATAIRE VARCHAR(90) NOT NULL,
    COULEUR VARCHAR(90) NOT NULL,
    PRIXUNITAIRE NUMERIC(19, 4) NOT NULL,
    UTILISATIONWMSID INT4 NOT NULL,
    UNITEMESUREMATIEREPREMIEREID INT4 NOT NULL,
    CLASSEMATIEREPREMIEREID INT4 NOT NULL,
    CATEGORIETISSUSID INT4 NOT NULL,
    STOCKTISSUID INT4 NOT NULL,
    COMMENTAIRE TEXT,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

ALTER TABLE SORTIETISSU
    ADD CONSTRAINT FKSORTIETISS994277 FOREIGN KEY (
        FAMILLETISSUSID
    )
        REFERENCES FAMILLETISSUS (
            ID
        );

ALTER TABLE SORTIETISSU
    ADD CONSTRAINT FKSORTIETISS252962 FOREIGN KEY (
        STOCKTISSUID
    )
        REFERENCES STOCKTISSU (
            ID
        );

ALTER TABLE SORTIETISSU
    ADD CONSTRAINT FKSORTIETISS810155 FOREIGN KEY (
        UTILISATIONWMSID
    )
        REFERENCES UTILISATIONWMS (
            ID
        );

ALTER TABLE SORTIETISSU
    ADD CONSTRAINT FKSORTIETISS102993 FOREIGN KEY (
        UNITEMESUREMATIEREPREMIEREID
    )
        REFERENCES UNITEMESUREMATIEREPREMIERE (
            ID
        );

ALTER TABLE SORTIETISSU
    ADD CONSTRAINT FKSORTIETISS267717 FOREIGN KEY (
        CLASSEMATIEREPREMIEREID
    )
        REFERENCES CLASSEMATIEREPREMIERE (
            ID
        );

ALTER TABLE SORTIETISSU
    ADD CONSTRAINT FKSORTIETISS884725 FOREIGN KEY (
        CATEGORIETISSUSID
    )
        REFERENCES CATEGORIETISSUS (
            ID
        );

ALTER TABLE SORTIETISSU
    ADD CONSTRAINT FKSORTIETISS575847 FOREIGN KEY (
        IDFOURNISSEUR
    )
        REFERENCES TIERS (
            ID
        );

ALTER TABLE SORTIETISSU
    ADD CONSTRAINT FKSORTIETISS886455 FOREIGN KEY (
        IDCLIENT
    )
        REFERENCES TIERS (
            ID
        );

CREATE TABLE RETOUR_TISSU (
    IDSORTIETISSU INT4 NOT NULL,
    QTERETOUR NUMERIC(19, 5) NOT NULL,
    DATERETOUR DATE NOT NULL
);

ALTER TABLE RETOUR_TISSU
    ADD CONSTRAINT FKRETOUR_TIS971470 FOREIGN KEY (
        IDSORTIETISSU
    )
        REFERENCES SORTIETISSU (
            ID
        );
