CREATE TABLE SECTIONWMS (
    ID SERIAL NOT NULL,
    SECTION VARCHAR(90) NOT NULL,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

--? Efa misy
-- CREATE TABLE CLASSEMATIEREPREMIERE (
--     ID INT4 NOT NULL,
--     DESIGNATION VARCHAR(255) NOT NULL,
--     ETAT INT4 DEFAULT 0 NOT NULL,
--     PRIMARY KEY (ID)
-- );
--TODO Modifier la base
CREATE TABLE RACK (
    ID SERIAL NOT NULL,
    IDSECTIONWMS INT4 NOT NULL,
    DESIGNATION VARCHAR(255) NOT NULL,
    LARGEUR NUMERIC(19, 5) NOT NULL,
    LONGUEUR NUMERIC(19, 5) NOT NULL,
    HAUTEUR NUMERIC(19, 5) NOT NULL,
    COMMENTAIRE TEXT,
    IDCATEGORIETISSUS INT4 NOT NULL,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

--?Efa misy
-- CREATE TABLE CATEGORIETISSUS (
--     ID INT4 NOT NULL,
--     CATEGORIE INT4 NOT NULL,
--     ETAT INT4 NOT NULL,
--     PRIMARY KEY (ID)
-- );

CREATE TABLE CELLULE (
    ID SERIAL NOT NULL,
    DESIGNATION VARCHAR(255) NOT NULL,
    IDRACK INT4 NOT NULL,
    LARGEUR NUMERIC(19, 5) NOT NULL,
    LONGUEUR NUMERIC(19, 5) NOT NULL,
    HAUTEUR NUMERIC(19, 0) NOT NULL,
    IDCLASSEMATIEREPREMIERE INT4 NOT NULL,
    COMMENTAIRE TEXT,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE PARITE (
    ID SERIAL NOT NULL,
    DATEPARITE DATE NOT NULL,
    DEVISEEURO NUMERIC(19, 5) NOT NULL,
    DEVISEDOLLAR NUMERIC(19, 5) NOT NULL,
    VALEUR NUMERIC(19, 5),
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE UTILISATIONWMS (
    ID SERIAL NOT NULL,
    UTILISATION VARCHAR(80) NOT NULL,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

--?Efa misy
-- CREATE TABLE UNITEMESUREMATIEREPREMIERE (
--     ID SERIAL NOT NULL,
--     UNITE_MESURE VARCHAR(25) NOT NULL,
--     ETAT INT4 DEFAULT 0 NOT NULL,
--     PRIMARY KEY (ID)
-- );

--?Efa misy
-- CREATE TABLE UNITEMONETAIRE (
--     ID SERIAL NOT NULL,
--     UNITE VARCHAR(25) NOT NULL,
--     ETAT INT4 DEFAULT 0 NOT NULL,
--     PRIMARY KEY (ID)
-- );

CREATE TABLE ENTREECT (
    ID SERIAL PRIMARY KEY,
    DATEENTREE DATE NOT NULL,
    DATEFACTURATION DATE NOT NULL,
    IDCATEGORIETISSUS INT4 NOT NULL REFERENCES CATEGORIETISSUS(ID),
    IDCLASSEMATIEREPREMIERE INT4 NOT NULL REFERENCES CLASSEMATIEREPREMIERE(ID),
    IDUTILISATIONWMS INT4 NOT NULL REFERENCES UTILISATIONWMS(ID),
    IDDONNEBC INT4 DEFAULT NULL REFERENCES DONNEBC(ID),
    NUMEROBC VARCHAR(90) NOT NULL,
    NUMEROBL VARCHAR(90) NOT NULL,
    NUMEROFACTURE VARCHAR(90) NOT NULL,
    FOURNISSEUR VARCHAR(90) NOT NULL,
    CLIENT VARCHAR(90) NOT NULL,
    MODELE VARCHAR(90) NOT NULL,
    SAISON VARCHAR(90) NOT NULL,
    DESIGNATION VARCHAR(255) NOT NULL,
    REFTISSU VARCHAR(255) NOT NULL,
    COMPOSITION VARCHAR(90) NOT NULL,
    COULEUR VARCHAR(255) NOT NULL,
    LAIZE DOUBLE PRECISION NOT NULL,
    QTECOMMANDE DOUBLE PRECISION NOT NULL,
    IDUNITEMESUREMATIEREPREMIERE INT4 NOT NULL REFERENCES UNITEMESUREMATIEREPREMIERE(ID),
    QTERECU DOUBLE PRECISION NOT NULL,
    TAUXECART DOUBLE PRECISION NOT NULL,
    NBROULEAU DOUBLE PRECISION NOT NULL,
    NBLOT DOUBLE PRECISION NOT NULL,
    PRIXUNITAIRE DOUBLE PRECISION NOT NULL,
    IDUNITEMONETAIRE INT4 NOT NULL REFERENCES UNITEMONETAIRE,
    RESTERECEVOIR DOUBLE PRECISION NOT NULL,
    IDCELLULE INT4 NOT NULL REFERENCES CELLULE(ID),
    FRET VARCHAR(200) NOT NULL,
    IMAGE TEXT DEFAULT NULL,
    COMMENTAIRE TEXT DEFAULT NULL,
    ETAT INT4 DEFAULT 0
);

--?Efa misy
-- CREATE TABLE DEMANDECLIENT (
--     ID SERIAL NOT NULL,
--     PRIMARY KEY (ID)
-- );

CREATE TABLE STOCKCT (
    ID SERIAL PRIMARY KEY,
    DATEENTREE DATE NOT NULL,
    DATEFACTURATION DATE NOT NULL,
    IDCATEGORIETISSUS INT4 NOT NULL REFERENCES CATEGORIETISSUS(ID),
    IDCLASSEMATIEREPREMIERE INT4 NOT NULL REFERENCES CLASSEMATIEREPREMIERE(ID),
    IDUTILISATIONWMS INT4 NOT NULL REFERENCES UTILISATIONWMS(ID),
    IDDONNEBC INT4 DEFAULT NULL REFERENCES DONNEBC(ID),
    NUMEROBC VARCHAR(90) NOT NULL,
    NUMEROBL VARCHAR(90) NOT NULL,
    NUMEROFACTURE VARCHAR(90) NOT NULL,
    FOURNISSEUR VARCHAR(90) NOT NULL,
    CLIENT VARCHAR(90) NOT NULL,
    MODELE VARCHAR(90) NOT NULL,
    SAISON VARCHAR(90) NOT NULL,
    DESIGNATION VARCHAR(255) NOT NULL,
    REFTISSU VARCHAR(255) NOT NULL,
    COMPOSITION VARCHAR(90) NOT NULL,
    COULEUR VARCHAR(255) NOT NULL,
    LAIZE DOUBLE PRECISION NOT NULL,
    QTECOMMANDE DOUBLE PRECISION NOT NULL,
    IDUNITEMESUREMATIEREPREMIERE INT4 NOT NULL REFERENCES UNITEMESUREMATIEREPREMIERE(ID),
    QTERECU DOUBLE PRECISION NOT NULL,
    TAUXECART DOUBLE PRECISION NOT NULL,
    NBROULEAU DOUBLE PRECISION NOT NULL,
    NBLOT DOUBLE PRECISION NOT NULL,
    PRIXUNITAIRE DOUBLE PRECISION NOT NULL,
    IDUNITEMONETAIRE INT4 NOT NULL REFERENCES UNITEMONETAIRE,
    RESTERECEVOIR DOUBLE PRECISION NOT NULL,
    IDCELLULE INT4 NOT NULL REFERENCES CELLULE(ID),
    FRET VARCHAR(200) NOT NULL,
    IMAGE TEXT DEFAULT NULL,
    COMMENTAIRE TEXT DEFAULT NULL,
    ETAT INT4 DEFAULT 0
);

--TODO : A faire
-- CREATE TABLE BCINTERNE (
--     ID SERIAL NOT NULL,
--     DATEBCINTERNE DATE NOT NULL,
--     PRIMARY KEY (ID)
-- );

ALTER TABLE RACK
    ADD CONSTRAINT FKRACK155234 FOREIGN KEY (
        IDSECTIONWMS
    )
        REFERENCES SECTIONWMS (
            ID
        );

ALTER TABLE RACK
    ADD CONSTRAINT FKRACK560157 FOREIGN KEY (
        IDCATEGORIETISSUS
    )
        REFERENCES CATEGORIETISSUS (
            ID
        );

ALTER TABLE CELLULE
    ADD CONSTRAINT FKCELLULE350976 FOREIGN KEY (
        IDRACK
    )
        REFERENCES RACK (
            ID
        );

ALTER TABLE STOCKCT
    ADD CONSTRAINT FKSTOCKCT532110 FOREIGN KEY (
        IDUTILISATIONWMS
    )
        REFERENCES UTILISATIONWMS (
            ID
        );

ALTER TABLE STOCKCT
    ADD CONSTRAINT FKSTOCKCT785473 FOREIGN KEY (
        DEMANDECLIENTID
    )
        REFERENCES DEMANDECLIENT (
            ID
        );

ALTER TABLE STOCKCT
    ADD CONSTRAINT FKSTOCKCT49326 FOREIGN KEY (
        UNITEMESUREMATIEREPREMIEREID
    )
        REFERENCES UNITEMESUREMATIEREPREMIERE (
            ID
        );

ALTER TABLE STOCKCT
    ADD CONSTRAINT FKSTOCKCT55792 FOREIGN KEY (
        CELLULEID
    )
        REFERENCES CELLULE (
            ID
        );

ALTER TABLE STOCKCT
    ADD CONSTRAINT FKSTOCKCT859822 FOREIGN KEY (
        UNITEMONETAIREID
    )
        REFERENCES UNITEMONETAIRE (
            ID
        );

ALTER TABLE CELLULE
    ADD CONSTRAINT FKCELLULE793135 FOREIGN KEY (
        IDCLASSEMATIEREPREMIERE
    )
        REFERENCES CLASSEMATIEREPREMIERE (
            ID
        );
