DROP TABLE IF EXISTS STOCKCT CASCADE;

DROP TABLE IF EXISTS ENTREECT CASCADE;

DROP TABLE IF EXISTS CELLULE CASCADE;

DROP TABLE IF EXISTS RACK CASCADE;

DROP TABLE IF EXISTS SECTIONWMS CASCADE;

DROP TABLE IF EXISTS PARITE CASCADE;

DROP TABLE IF EXISTS UTILISATIONWMS CASCADE;

--!VIEW!--
DROP VIEW IF EXISTS V_PARITE CASCADE;

DROP VIEW IF EXISTS V_ENTREE_CT CASCADE;
