CREATE OR REPLACE VIEW V_PARITE AS
    SELECT
        P.DEVISEEURO,
        P.DEVISEDOLLAR,
        P.VALEUR,
        EXTRACT(MONTH FROM P.DATEPARITE) AS MOIS,
        EXTRACT(YEAR FROM P.DATEPARITE)  AS ANNEE
    FROM
        PARITE P;

CREATE OR REPLACE VIEW V_ENTREE_CT AS
    SELECT
        E.DATEENTREE,
        E.DATEFACTURATION,
        E.IDCATEGORIETISSUS,
        CAT.CATEGORIE,
        E.IDCLASSEMATIEREPREMIERE,
        CMP.CLASSE,
        E.IDUTILISATIONWMS,
        U.UTILISATION,
        E.IDDONNEBC,
        E.NUMEROBC,
        E.NUMEROBL,
        E.NUMEROFACTURE,
        E.FOURNISSEUR,
        E.CLIENT,
        E.MODELE,
        E.SAISON,
        E.DESIGNATION                  AS DES_TISSU,
        E.REFTISSU,
        E.COMPOSITION,
        E.COULEUR,
        E.LAIZE,
        E.QTECOMMANDE,
        E.IDUNITEMESUREMATIEREPREMIERE,
        UMP.UNITE_MESURE               AS UNITE_TISSU,
        E.QTERECU,
        E.TAUXECART,
        E.NBROULEAU,
        E.NBLOT,
        E.PRIXUNITAIRE,
        E.IDUNITEMONETAIRE,
        UM.UNITE                       AS UNITEMONETAIRE,
        E.RESTERECEVOIR,
        R.DESIGNATION                  AS DES_RACK,
        C.IDRACK,
        C.DESIGNATION                  AS DES_CELLULE,
        C.ID                           AS IDCELLULE,
        E.FRET,
        E.COMMENTAIRE,
        P.VALEUR                       AS PARITE
    FROM
        ENTREECT                   E
        JOIN CELLULE C
        ON C.ID=E.IDCELLULE
        JOIN RACK R
        ON R.ID=C.IDRACK
        JOIN CATEGORIETISSUS CAT
        ON CAT.ID=E.IDCATEGORIETISSUS
        JOIN CLASSEMATIEREPREMIERE CMP
        ON CMP.ID=E.IDCLASSEMATIEREPREMIERE
        JOIN UTILISATIONWMS U
        ON U.ID=E.IDUTILISATIONWMS
        JOIN UNITEMESUREMATIEREPREMIERE UMP
        ON UMP.ID=E.IDUNITEMESUREMATIEREPREMIERE
        JOIN UNITEMONETAIRE UM
        ON UM.ID=E.IDUNITEMONETAIRE
        JOIN V_PARITE P
        ON P.MOIS= EXTRACT(MONTH FROM E.DATEENTREE)
        AND P.ANNEE=EXTRACT(YEAR FROM E.DATEENTREE);
