CREATE OR REPLACE VIEW V_PARITE AS
    SELECT
        P.DEVISEEURO,
        P.DEVISEDOLLAR,
        P.VALEUR,
        EXTRACT(MONTH FROM P.DATEPARITE) AS MOIS,
        EXTRACT(YEAR FROM P.DATEPARITE)  AS ANNEE
    FROM
        PARITE P;

CREATE OR REPLACE VIEW V_RACK_CELLULE AS
    SELECT
        C.ID                      AS IDCELLULE,
        R.DESIGNATION
        || ''
        || C.DESIGNATION          AS DESIGNATION,
        R.IDSECTIONWMS,
        S.SECTION,
        R.ID                      AS IDRACK,
        R.DESIGNATION             AS DES_RACK,
        R.IDCATEGORIETISSU,
        CT.CATEGORIE              AS CAT_TISSU,
        C.DESIGNATION             AS DES_CELLULE,
        C.IDCLASSEMATIEREPREMIERE,
        CMP.CLASSE
    FROM
        CELLULE               C
        JOIN RACK R
        ON C.IDRACK = R.ID
        JOIN SECTIONWMS S
        ON R.IDSECTIONWMS = S.ID
        JOIN CATEGORIETISSUS CT
        ON R.IDCATEGORIETISSU=CT.ID
        JOIN CLASSEMATIEREPREMIERE CMP
        ON C.IDCLASSEMATIEREPREMIERE=CMP.ID
    WHERE
        C.ETAT=0;

CREATE OR REPLACE VIEW V_ENTREE_TISSU AS
    SELECT
        E.DATEENTREE,
        E.DATEFACTURATION,
        E.IDCATEGORIETISSUS,
        CT.CATEGORIE,
        E.IDCLASSEMATIEREPREMIERE,
        CMP.CLASSE,
        E.IDUTILISATIONWMS,
        UW.UTILISATION,
        E.IDDONNEBC,
        E.NUMEROBC,
        E.NUMEROBL,
        E.NUMEROFACTURE,
        E.IDFOURNISSEUR,
        TF.NOMTIER                     AS FOURNISSEUR,
        E.IDCLIENT,
        TC.NOMTIER                     AS CLIENT,
        E.MODELE,
        E.SAISON,
        E.DESIGNATION                  AS DES_TISSU,
        E.REFTISSU,
        E.COMPOSITION,
        E.COULEUR,
        E.LAIZE,
        E.QTECOMMANDE,
        E.IDUNITEMESUREMATIEREPREMIERE,
        UMMP.UNITE_MESURE,
        E.QTERECU,
        E.TAUXECART,
        E.NBROULEAU,
        E.NBLOT,
        E.PRIXUNITAIRE,
        E.IDUNITEMONETAIRE,
        UM.UNITE                       AS UNITE_MONETAIRE,
        E.RESTERECEVOIR,
        E.FRET,
        E.COMMENTAIRE,
        E.IDFAMILLETISSUS,
        FT.FAMILLE_TISSUS,
        VP.VALEUR
    FROM
        ENTREETISSU                E
        JOIN CATEGORIETISSUS CT
        ON CT.ID= E.IDCATEGORIETISSUS
        JOIN CLASSEMATIEREPREMIERE CMP
        ON CMP.ID=E.IDCLASSEMATIEREPREMIERE
        JOIN UTILISATIONWMS UW
        ON UW.ID = E.IDUTILISATIONWMS
        LEFT JOIN DONNEBC DBC
        ON DBC.ID=E.IDDONNEBC
        JOIN UNITEMESUREMATIEREPREMIERE UMMP
        ON UMMP.ID=E.IDUNITEMESUREMATIEREPREMIERE
        JOIN UNITEMONETAIRE UM
        ON UM.ID = E.IDUNITEMONETAIRE
        JOIN FAMILLETISSUS FT
        ON FT.ID=E.IDFAMILLETISSUS
        LEFT JOIN V_PARITE VP
        ON VP.MOIS= EXTRACT(MONTH FROM E.DATEFACTURATION)
        AND VP.ANNEE=EXTRACT(YEAR FROM E.DATEFACTURATION)
        JOIN TIERS TF
        ON TF.ID=E.IDFOURNISSEUR
        JOIN TIERS TC
        ON TC.ID=E.IDCLIENT;

CREATE OR REPLACE VIEW V_SOMME_ENTREE_TISSU AS
    SELECT
        IDSTOCKTISSU,
        SUM(QTERECU) AS SOMMEQTERECU
    FROM
        ENTREETISSU
    GROUP BY
        IDSTOCKTISSU;

CREATE OR REPLACE VIEW V_SOMME_SORTIE_TISSU AS
    SELECT
        IDSTOCKTISSU,
        SUM(QTESORTIE) AS SOMMEQTESORTIE
    FROM
        SORTIETISSU
    GROUP BY
        IDSTOCKTISSU;

CREATE OR REPLACE VIEW V_STOCK_TISSU AS
    SELECT
        ST.*,
        CT.CATEGORIE,
        CMP.CLASSE,
        UW.UTILISATION,
        TF.NOMTIER          AS FOURNISSEUR,
        VSET.SOMMEQTERECU,
        VSST.SOMMEQTESORTIE
    FROM
        STOCKTISSU            ST
        JOIN CATEGORIETISSUS CT
        ON CT.ID= ST.IDCATEGORIETISSUS
        JOIN CLASSEMATIEREPREMIERE CMP
        ON CMP.ID=ST.IDCLASSEMATIEREPREMIERE
        JOIN UTILISATIONWMS UW
        ON UW.ID = ST.IDUTILISATIONWMS
        JOIN TIERS TF
        ON TF.ID=ST.IDFOURNISSEUR
        LEFT JOIN V_SOMME_ENTREE_TISSU VSET
        ON VSET.IDSTOCKTISSU=ST.ID
        LEFT JOIN V_SOMME_SORTIE_TISSU VSST
        ON VSST.IDSTOCKTISSU=ST.ID;

CREATE OR REPLACE VIEW V_SORTIE_TISSU AS
    SELECT
        ST.*,
        CT.CATEGORIE,
        CMP.CLASSE,
        UW.UTILISATION,
        TF.NOMTIER     AS FOURNISSEUR,
        TC.NOMTIER     AS CLIENT
    FROM
        SORTIETISSU           ST
        JOIN CATEGORIETISSUS CT
        ON CT.ID= ST.IDCATEGORIETISSUS
        JOIN CLASSEMATIEREPREMIERE CMP
        ON CMP.ID=ST.IDCLASSEMATIEREPREMIERE
        JOIN UTILISATIONWMS UW
        ON UW.ID = ST.IDUTILISATIONWMS
        JOIN TIERS TF
        ON TF.ID=ST.IDFOURNISSEUR
        JOIN TIERS TC
        ON TC.ID=ST.IDCLIENT;

CREATE OR REPLACE VIEW V_RETOUR_TISSU AS
    SELECT
        RT.IDSORTIETISSU,
        RT.QTERETOUR,
        RT.DATERETOUR,
        RT.ETAT          AS ETAT_RETOUR,
        ST .*,
        CT.CATEGORIE,
        CMP.CLASSE,
        UW.UTILISATION,
        TF.NOMTIER       AS FOURNISSEUR,
        TC.NOMTIER       AS CLIENT
    FROM
        RETOUR_TISSU          RT
        JOIN SORTIETISSU ST
        ON ST.ID=RT.IDSORTIETISSU
        JOIN CATEGORIETISSUS CT
        ON CT.ID= ST.IDCATEGORIETISSUS
        JOIN CLASSEMATIEREPREMIERE CMP
        ON CMP.ID=ST.IDCLASSEMATIEREPREMIERE
        JOIN UTILISATIONWMS UW
        ON UW.ID = ST.IDUTILISATIONWMS
        JOIN TIERS TF
        ON TF.ID=ST.IDFOURNISSEUR
        JOIN TIERS TC
        ON TC.ID=ST.IDCLIENT;

CREATE OR REPLACE VIEW V_RESERVATION_TISSU AS
    SELECT
        ST.*,
        RT.ID              AS IDRESERVATION,
        RT.DATERESERVATION,
        RT.QTERESERVE,
        RT.COMMENTAIRE     AS COMMENT_RESERVATION,
        RT.VALIDATION,
        RT.ETAT            AS ETAT_RESERVATION,
        CT.CATEGORIE,
        CMP.CLASSE,
        UW.UTILISATION,
        TF.NOMTIER         AS FOURNISSEUR
    FROM
        RESERVATIONTISSU      RT
        JOIN STOCKTISSU ST
        ON ST.ID=RT.IDSTOCKTISSU
        JOIN CATEGORIETISSUS CT
        ON CT.ID= ST.IDCATEGORIETISSUS
        JOIN CLASSEMATIEREPREMIERE CMP
        ON CMP.ID=ST.IDCLASSEMATIEREPREMIERE
        JOIN UTILISATIONWMS UW
        ON UW.ID = ST.IDUTILISATIONWMS
        JOIN TIERS TF
        ON TF.ID=ST.IDFOURNISSEUR;

CREATE OR REPLACE VIEW V_TOTAL_ENTREE_TISSU AS
    SELECT
        COUNT(ET.ID)       AS ENTREE,
        ET.IDFAMILLETISSUS
    FROM
        ENTREETISSU ET
    GROUP BY
        ET.IDFAMILLETISSUS;

CREATE OR REPLACE VIEW V_PRIX_TOTAL_TISSU_FAMILLE_ENTREE AS
    SELECT
        SUM(ET.PRIXUNITAIRE*ET.QTERECU) AS PRIXTOTAL,
        ET.IDFAMILLETISSUS
    FROM
        ENTREETISSU ET
    GROUP BY
        ET.IDFAMILLETISSUS;

CREATE OR REPLACE VIEW V_TOTAL_METRAGE_TISSU_FAMILLE_ENTREE AS
    SELECT
        SUM(ET.QTERECU)    AS METRAGE,
        ET.IDFAMILLETISSUS
    FROM
        ENTREETISSU ET
    GROUP BY
        ET.IDFAMILLETISSUS;

CREATE
OR REPLACE VIEW V_ENTREE_PAR_MOIS_TISSU AS

SELECT
    COUNT(ET.ID)                      AS ENTREE,
    ET.IDFAMILLETISSUS,
    EXTRACT(MONTH FROM ET.DATEENTREE) AS MOIS,
    EXTRACT(YEAR FROM ET.DATEENTREE)  AS ANNEE
FROM
    ENTREETISSU ET
GROUP BY
    ET.IDFAMILLETISSUS,
    EXTRACT(MONTH FROM ET.DATEENTREE),
    EXTRACT(YEAR FROM ET.DATEENTREE);

CREATE OR REPLACE VIEW V_TOTAL_STOCK_TISSU AS
    SELECT
        COUNT(ST.ID)       AS STOCK,
        ST.IDFAMILLETISSUS
    FROM
        STOCKTISSU ST
    WHERE
        ST.QTESTOCK > 0
    GROUP BY
        ST.IDFAMILLETISSUS;

CREATE OR REPLACE VIEW V_PRIX_TOTAL_TISSU_FAMILLE_STOCK AS
    SELECT
        SUM(ST.PRIXUNITAIRE*ST.QTESTOCK) AS PRIXTOTAL,
        ST.IDFAMILLETISSUS
    FROM
        STOCKTISSU ST
    GROUP BY
        ST.IDFAMILLETISSUS;

CREATE OR REPLACE VIEW V_TOTAL_METRAGE_TISSU_FAMILLE_STOCK AS
    SELECT
        SUM(ST.QTESTOCK)   AS METRAGE,
        ST.IDFAMILLETISSUS
    FROM
        STOCKTISSU ST
    GROUP BY
        ST.IDFAMILLETISSUS;
