CREATE TABLE SECTIONWMS (
    ID SERIAL NOT NULL,
    SECTION VARCHAR(90) NOT NULL,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE CLASSEMATIEREPREMIERE (
    ID SERIAL NOT NULL,
    DESIGNATION VARCHAR(255) NOT NULL,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE RACK (
    ID SERIAL NOT NULL,
    IDSECTIONWMS INT4 NOT NULL,
    DESIGNATION VARCHAR(255) NOT NULL,
    LARGEUR NUMERIC(19, 5) NOT NULL,
    LONGUEUR NUMERIC(19, 5) NOT NULL,
    HAUTEUR NUMERIC(19, 5) NOT NULL,
    COMMENTAIRE VARCHAR(255),
    IDCATEGORIETISSU INT4 NOT NULL,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE CATEGORIETISSUS (
    ID SERIAL NOT NULL,
    CATEGORIE INT4 NOT NULL,
    ETAT INT4 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE CELLULE (
    ID SERIAL NOT NULL,
    DESIGNATION VARCHAR(255) NOT NULL,
    IDRACK INT4 NOT NULL,
    LARGEUR NUMERIC(19, 5) NOT NULL,
    LONGUEUR NUMERIC(19, 5) NOT NULL,
    HAUTEUR NUMERIC(19, 0) NOT NULL,
    IDCLASSEMATIEREPREMIERE INT4 NOT NULL,
    COMMENTAIRE VARCHAR(255),
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE PARITE (
    ID SERIAL NOT NULL,
    DATEPARITE DATE NOT NULL,
    DEVISEEURO NUMERIC(19, 5) NOT NULL,
    DEVISEDOLLAR NUMERIC(19, 5) NOT NULL,
    VALEUR NUMERIC(19, 5),
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE UTILISATIONWMS (
    ID SERIAL NOT NULL,
    UTILISATION VARCHAR(80) NOT NULL,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE UNITEMESUREMATIEREPREMIERE (
    ID SERIAL NOT NULL,
    UNITE_MESURE VARCHAR(25) NOT NULL,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE UNITEMONETAIRE (
    ID SERIAL NOT NULL,
    UNITE VARCHAR(25) NOT NULL,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE ENTREETISSU (
    ID SERIAL NOT NULL,
    IDFAMILLETISSUS INT4 NOT NULL,
    DATEENTREE DATE NOT NULL,
    DATEFACTURATION DATE NOT NULL,
    IDCATEGORIETISSUS INT4 NOT NULL,
    IDCLASSEMATIEREPREMIERE INT4 NOT NULL,
    IDUTILISATIONWMS INT4 NOT NULL,
    IDDONNEBC INT4,
    NUMEROBC VARCHAR(90) NOT NULL,
    NUMEROBL VARCHAR(90) NOT NULL,
    NUMEROFACTURE VARCHAR(90) NOT NULL,
    IDFOURNISSEUR INT4,
    IDCLIENT INT4,
    MODELE VARCHAR(90) NOT NULL,
    SAISON VARCHAR(90) NOT NULL,
    DESIGNATION VARCHAR(255) NOT NULL,
    REFTISSU VARCHAR(255) NOT NULL,
    COMPOSITION VARCHAR(90) NOT NULL,
    COULEUR VARCHAR(90) NOT NULL,
    LAIZE VARCHAR(90) NOT NULL,
    QTECOMMANDE NUMERIC(19, 4) NOT NULL,
    IDUNITEMESUREMATIEREPREMIERE INT4,
    QTERECU NUMERIC(19, 4) NOT NULL,
    TAUXECART NUMERIC(19, 4) NOT NULL,
    NBROULEAU NUMERIC(19, 4) NOT NULL,
    NBLOT NUMERIC(19, 4) NOT NULL,
    PRIXUNITAIRE NUMERIC(19, 4) NOT NULL,
    IDUNITEMONETAIRE INT4 NOT NULL,
    RESTERECEVOIR NUMERIC(19, 4),
    FRET VARCHAR(90) NOT NULL,
    IMAGE TEXT,
    COMMENTAIRE TEXT,
    ETAT INT4 DEFAULT 0 NOT NULL,
    IDSTOCKTISSU INT4,
    GRAMMAGE NUMERIC(19, 4),
    PRIMARY KEY (ID)
);

CREATE TABLE BCINTERNE (
    ID SERIAL NOT NULL,
    DATEBCINTERNE DATE NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE FAMILLETISSUS (
    ID INT4 NOT NULL,
    FAMILLE_TISSUS VARCHAR(255) NOT NULL,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE CELLULE_ENTREETISSU (
    IDENTREETISSU INT4 NOT NULL,
    IDCELLULE INT4 NOT NULL,
    PRIMARY KEY (IDENTREETISSU, IDCELLULE)
);

CREATE TABLE DONNEBC (
    ID INT4 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE TIERS (
    ID INT4 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE STOCKTISSU (
    ID SERIAL NOT NULL,
    IDCATEGORIETISSUS INT4 NOT NULL,
    IDCLASSEMATIEREPREMIERE INT4 NOT NULL,
    IDUTILISATIONWMS INT4 NOT NULL,
    REFERENCE VARCHAR(90) NOT NULL,
    DESIGNATION VARCHAR(90) NOT NULL,
    COMPOSITION VARCHAR(90) NOT NULL,
    COULEUR VARCHAR(90) NOT NULL,
    IDFOURNISSEUR INT4 NOT NULL,
    SAISON VARCHAR(90) NOT NULL,
    LAIZE VARCHAR(90) NOT NULL,
    QTESTOCK INT4,
    PRIXUNITAIRE NUMERIC(19, 4) NOT NULL,
    IDUNITEMESUREMATIEREPREMIERE INT4 NOT NULL,
    IDFAMILLETISSUS INT4 NOT NULL,
    COMMENTAIRE TEXT,
    IMAGE TEXT,
    ETAT INT4 DEFAULT 0 NOT NULL,
    OBSOLETE INT4,
    GRAMMAGE NUMERIC(19, 4),
    PRIMARY KEY (ID)
);

CREATE TABLE STOCKTISSU_TIERS_MODELE (
    IDSTOCKTISSU INT4 NOT NULL,
    IDCLIENT INT4 NOT NULL,
    MODELE VARCHAR(90) NOT NULL,
    PRIMARY KEY (IDSTOCKTISSU, IDCLIENT)
);

CREATE TABLE PRIXUNITAIRESTOCKTISSU (
    ID INT4 NOT NULL,
    DATEPRIX DATE NOT NULL,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE RESERVATIONTISSU (
    ID SERIAL NOT NULL,
    DATERESERVATION DATE NOT NULL,
    IDSTOCKTISSU INT4 NOT NULL,
    QTERESERVE NUMERIC(19, 4) NOT NULL,
    COMMENTAIRE TEXT,
    VALIDATION INT4 DEFAULT 1 NOT NULL,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE CELLULE_STOCKTISSU (
    IDCELLULE INT4 NOT NULL,
    IDSTOCKTISSU INT4 NOT NULL,
    PRIMARY KEY (IDCELLULE, IDSTOCKTISSU)
);

CREATE TABLE SORTIETISSU (
    ID SERIAL NOT NULL,
    DATESORTIE DATE NOT NULL,
    NUMBCI VARCHAR(255) NOT NULL,
    IDFAMILLETISSUS INT4 NOT NULL,
    QTESORTIE NUMERIC(19, 4) NOT NULL,
    DESIGNATION VARCHAR(90) NOT NULL,
    REFERENCE VARCHAR(90) NOT NULL,
    MODELE VARCHAR(90) NOT NULL,
    SAISON VARCHAR(90) NOT NULL,
    RECEVEUR VARCHAR(90) NOT NULL,
    LAIZE VARCHAR(90) NOT NULL,
    IDFOURNISSEUR INT4 NOT NULL,
    IDCLIENT INT4 NOT NULL,
    COMPOSITION VARCHAR(90) NOT NULL,
    DESTINATAIRE VARCHAR(90) NOT NULL,
    COULEUR VARCHAR(90) NOT NULL,
    PRIXUNITAIRE NUMERIC(19, 4) NOT NULL,
    IDUTILISATIONWMS INT4 NOT NULL,
    IDUNITEMESUREMATIEREPREMIERE INT4 NOT NULL,
    IDCLASSEMATIEREPREMIERE INT4 NOT NULL,
    IDCATEGORIETISSUS INT4 NOT NULL,
    IDSTOCKTISSU INT4 NOT NULL,
    COMMENTAIRE TEXT,
    ETAT INT4 DEFAULT 0 NOT NULL,
    GRAMMAGE NUMERIC(19, 4),
    PRIMARY KEY (ID)
);

CREATE TABLE RETOUR_TISSU (
    IDSORTIETISSU INT4 NOT NULL,
    QTERETOUR NUMERIC(19, 5) NOT NULL,
    DATERETOUR DATE NOT NULL,
    ETAT INT4 DEFAULT 0 NOT NULL
);

CREATE TABLE ENTREECONSOMMABLE (
    ID SERIAL NOT NULL,
    DATEENTREE DATE NOT NULL,
    NUMBC VARCHAR(90),
    NUMBL VARCHAR(90),
    IDFOURNISSEUR INT4 NOT NULL,
    IDCLIENT INT4 NOT NULL,
    SAISON VARCHAR(90) NOT NULL,
    DESIGNATION VARCHAR(90) NOT NULL,
    REFERENCE VARCHAR(90) NOT NULL,
    COULEUR VARCHAR(90) NOT NULL,
    MODELE VARCHAR(90) NOT NULL,
    QTECOMMANDE NUMERIC(19, 5) NOT NULL,
    IDUNITEMESUREMATIEREPREMIERE INT4 NOT NULL,
    QTERECU INT4,
    RESTERECEVOIR INT4,
    PRIXUNITAIRE INT4,
    IDUNITEMONETAIRE INT4 NOT NULL,
    FRET INT4,
    COMMENTAIRE TEXT,
    IMAGE TEXT,
    IDSTOCKCONSOMMABLE INT4 NOT NULL,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE CELLULE_ENTREECONSOMMABLE (
    IDCELLULE INT4 NOT NULL,
    IDENTREECONSOMMABLE INT4 NOT NULL,
    PRIMARY KEY (IDCELLULE, IDENTREECONSOMMABLE)
);

CREATE TABLE STOCKCONSOMMABLE (
    ID SERIAL NOT NULL,
    DESIGNATION VARCHAR(90) NOT NULL,
    REFERENCE VARCHAR(90) NOT NULL,
    COULEUR INT4,
    IDFOURNISSEUR INT4 NOT NULL,
    SAISON VARCHAR(90) NOT NULL,
    QTESTOCK NUMERIC(19, 5),
    PRIXUNITAIRE NUMERIC(19, 5) NOT NULL,
    IDUNITEMESUREMATIEREPREMIERE INT4 NOT NULL,
    COMMENTAIRE TEXT,
    IMAGE TEXT,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE CLIENT_STOCKCONSOMMABLE (
    IDCLIENT INT4 NOT NULL,
    IDSTOCKCONSOMMABLE INT4 NOT NULL,
    MODELE VARCHAR(90) NOT NULL,
    PRIMARY KEY (IDCLIENT, IDSTOCKCONSOMMABLE)
);

CREATE TABLE SOTIECONSOMMABLE (
    ID SERIAL NOT NULL,
    DATESORTIE DATE NOT NULL,
    NUMBCI INT4,
    DESIGNATION VARCHAR(90) NOT NULL,
    REFERENCE VARCHAR(90) NOT NULL,
    COULEUR VARCHAR(90) NOT NULL,
    TIERSID INT4 NOT NULL,
    IDCLIENT INT4 NOT NULL,
    IDFOURNISSEUR INT4 NOT NULL,
    MODELE VARCHAR(90) NOT NULL,
    SAISON VARCHAR(90) NOT NULL,
    DESTINATAIRE VARCHAR(90) NOT NULL,
    RECEVEUR VARCHAR(90) NOT NULL,
    QTESORTIE NUMERIC(19, 5),
    IDUNITEMESUREMATIEREPREMIERE INT4 NOT NULL,
    PRIXUNITAIRE INT4,
    COMMENTAIRE TEXT,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE FAMILLEACCESSOIRE (
    ID SERIAL NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE ENTREEACCESSOIRE (
    ID SERIAL NOT NULL,
    DATEENTREE DATE NOT NULL,
    DATEFACTURATION DATE NOT NULL,
    IDFOURNISSEUR INT4 NOT NULL,
    IDCLIENT INT4 NOT NULL,
    SAISON VARCHAR(90) NOT NULL,
    NUMBC VARCHAR(90) NOT NULL,
    MODELE VARCHAR(90) NOT NULL,
    IDFAMILLEACCESSOIRE INT4 NOT NULL,
    IDCLASSEMATIEREPREMIERE INT4 NOT NULL,
    DESIGNATION VARCHAR(90) NOT NULL,
    REFERENCE VARCHAR(90) NOT NULL,
    COULEUR VARCHAR(90) NOT NULL,
    CODE VARCHAR(90) NOT NULL,
    QTEENTREE NUMERIC(19, 5) NOT NULL,
    IDUNITEMESUREMATIEREPREMIERE INT4 NOT NULL,
    PRIXUNITAIRE NUMERIC(19, 5) NOT NULL,
    IDUNITEMONETAIRE INT4 NOT NULL,
    RESTELIVRER NUMERIC(19, 5),
    COMMENTAIRE TEXT,
    IMAGE TEXT,
    ETAT INT4 DEFAULT 0 NOT NULL,
    QUALITE INT4 DEFAULT 1 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE RETOURCONSOMMABLE (
    IDSOTIECONSOMMABLE INT4 NOT NULL,
    DATERETOUR DATE NOT NULL,
    QTERETOUR NUMERIC(19, 5),
    ETAT INT4 DEFAULT 0 NOT NULL
);

CREATE TABLE CELLULE_STOCKCONSOMMABLE (
    IDCELLULE INT4 NOT NULL,
    IDSTOCKCONSOMMABLE INT4 NOT NULL,
    PRIMARY KEY (IDCELLULE, IDSTOCKCONSOMMABLE)
);

CREATE TABLE ENTREEACCESSOIRE_CELLULE (
    IDENTREEACCESSOIRE INT4 NOT NULL,
    IDCELLULE INT4 NOT NULL,
    PRIMARY KEY (IDENTREEACCESSOIRE, IDCELLULE)
);

CREATE TABLE STOCKACCESSOIRE (
    ID SERIAL NOT NULL,
    IDFAMILLEACCESSOIRE INT4 NOT NULL,
    IDFOURNISSEUR INT4 NOT NULL,
    CLASSEMATIEREPREMIEREID INT4 NOT NULL,
    DESIGNATION VARCHAR(90) NOT NULL,
    REFERENCE VARCHAR(90) NOT NULL,
    COULEUR VARCHAR(90) NOT NULL,
    CODE VARCHAR(90),
    QTESTOCK NUMERIC(19, 4) NOT NULL,
    UNITEMESUREMATIEREPREMIEREID INT4 NOT NULL,
    PRIXUNITAIRE NUMERIC(19, 5) NOT NULL,
    COMMENTAIRE TEXT,
    IMAGE TEXT,
    ETAT INT4 DEFAULT 0 NOT NULL,
    OBSOLETE INT4,
    PRIMARY KEY (ID)
);

CREATE TABLE STOCKACCESSOIRE_CELLULE (
    IDSTOCKACCESSOIRE INT4 NOT NULL,
    IDCELLULE INT4 NOT NULL,
    PRIMARY KEY (IDSTOCKACCESSOIRE, IDCELLULE)
);

CREATE TABLE CLIENT_STOCKACCESSOIRE (
    IDTIERS INT4 NOT NULL,
    IDSTOCKACCESSOIRE INT4 NOT NULL,
    MODELE VARCHAR(90) NOT NULL,
    PRIMARY KEY (IDTIERS, IDSTOCKACCESSOIRE)
);

CREATE TABLE SORTIEACCESSOIRE (
    ID SERIAL NOT NULL,
    DATESORTIE DATE NOT NULL,
    DESTINATAIRE VARCHAR(90) NOT NULL,
    RECEVEUR VARCHAR(90) NOT NULL,
    IDFAMILLEACCESSOIRE INT4 NOT NULL,
    DESIGNATION VARCHAR(90) NOT NULL,
    REFERENCE VARCHAR(90) NOT NULL,
    COULEUR VARCHAR(90) NOT NULL,
    IDFOURNISSEUR INT4 NOT NULL,
    IDCLIENT INT4 NOT NULL,
    MODELE VARCHAR(90) NOT NULL,
    IDCLASSEMATIEREPREMIERE INT4 NOT NULL,
    CODE VARCHAR(90),
    QTESORTIE NUMERIC(19, 4),
    COMMENTAIRE TEXT,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE RETOURACCESSOIRE (
    IDSORTIEACCESSOIRE INT4 NOT NULL,
    DATERETOUR DATE NOT NULL,
    QTERETOUR NUMERIC(19, 3) NOT NULL,
    ETAT INT4 DEFAULT 0 NOT NULL
);

CREATE TABLE WMS_TYPE (
    ID SERIAL NOT NULL,
    TYPE INT4 NOT NULL,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE FAMILLEWMS (
    ID SERIAL NOT NULL,
    IDWMS_TYPE INT4 NOT NULL,
    NOM VARCHAR(90) NOT NULL,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE ENTREEWMS (
    ID SERIAL NOT NULL,
    DATEENTREE DATE NOT NULL,
    DATEFACTURATION DATE NOT NULL,
    IDCLIENT INT4,
    IDFAMILLEWMS INT4 NOT NULL,
    IDFOURNISSEUR INT4 NOT NULL,
    NUMBC VARCHAR(90),
    MODELE VARCHAR(90) NOT NULL,
    IDCLASSEMATIEREPREMIERE INT4 NOT NULL,
    DESIGNATION VARCHAR(90) NOT NULL,
    REFERENCE VARCHAR(90) NOT NULL,
    COULEUR VARCHAR(90) NOT NULL,
    CODE VARCHAR(90),
    QTEENTREE NUMERIC(19, 3) NOT NULL,
    IDUNITEMESUREMATIEREPREMIERE INT4 NOT NULL,
    PRIXUNITAIRE NUMERIC(19, 5) NOT NULL,
    IDUNITEMONETAIRE INT4 NOT NULL,
    RESTERECEVOIR NUMERIC(19, 3),
    FRET VARCHAR(90),
    COMMENTAIRE TEXT,
    IMAGE TEXT,
    STOCKWMSID INT4 NOT NULL,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE STOCKWMS (
    ID SERIAL NOT NULL,
    IDCLIENT INT4 NOT NULL,
    IDFOURNISSEUR INT4 NOT NULL,
    IDFAMILLEWMS INT4 NOT NULL,
    MODELE VARCHAR(90) NOT NULL,
    IDCLASSEMATIEREPREMIERE INT4 NOT NULL,
    DESIGNATION VARCHAR(90) NOT NULL,
    REFERENCE VARCHAR(90) NOT NULL,
    COULEUR VARCHAR(90) NOT NULL,
    CODE VARCHAR(90),
    QTESTOCK NUMERIC(19, 3) NOT NULL,
    IDUNITEMESUREMATIEREPREMIERE INT4 NOT NULL,
    PRIXUNITAIRE NUMERIC(19, 5) NOT NULL,
    COMMENTAIRE TEXT,
    IMAGE TEXT,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE SORTIEWMS (
    ID SERIAL NOT NULL,
    DATESORTIE DATE NOT NULL,
    DESTINATAIRE VARCHAR(90),
    RECEVEUR VARCHAR(90),
    FAMILLEWMSID INT4 NOT NULL,
    DESIGNATION VARCHAR(90) NOT NULL,
    REFERENCE VARCHAR(90) NOT NULL,
    COULEUR VARCHAR(90) NOT NULL,
    IDCLIENT INT4 NOT NULL,
    IDFOURNISSEUR INT4 NOT NULL,
    MODELE VARCHAR(90) NOT NULL,
    IDCLASSEMATIEREPREMIERE INT4 NOT NULL,
    CODE VARCHAR(90),
    QTESORTIE NUMERIC(19, 3),
    PRIXUNITAIRE NUMERIC(19, 5) NOT NULL,
    IMAGE TEXT,
    COMMENTAIRE TEXT,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE ENTREEWMS_CELLULE (
    IDENTREEWMS INT4 NOT NULL,
    IDCELLULE INT4 NOT NULL,
    PRIMARY KEY (IDENTREEWMS, IDCELLULE)
);

CREATE TABLE STOCKWMS_CELLULE (
    IDSTOCKWMS INT4 NOT NULL,
    IDCELLULE INT4 NOT NULL,
    PRIMARY KEY (IDSTOCKWMS, IDCELLULE)
);

CREATE TABLE CLIENT_STOCKWMS (
    IDCLIENT INT4 NOT NULL,
    IDSTOCKWMS INT4 NOT NULL,
    MODELE VARCHAR(90) NOT NULL,
    PRIMARY KEY (IDCLIENT, IDSTOCKWMS)
);

CREATE TABLE QUALITEROULEAUTISSU (
    ID SERIAL NOT NULL,
    LOT INT4,
    IDENTREETISSU INT4 NOT NULL,
    LAIZE NUMERIC(19, 3) NOT NULL,
    METRAGE INT4,
    POIDS INT4,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE TESTCONFORMITETISSU (
    ID SERIAL NOT NULL,
    IDENTREETISSU INT4 NOT NULL,
    DATEDEBUT DATE NOT NULL,
    LAB_DIP TEXT NOT NULL,
    SWATCH TEXT NOT NULL,
    QTECDE NUMERIC(19, 3) NOT NULL,
    QTERECUPL NUMERIC(19, 3) NOT NULL,
    LAIZECDE NUMERIC(19, 3) NOT NULL,
    OBSERVATION TEXT NOT NULL,
    QTECDEKG NUMERIC(19, 3) NOT NULL,
    QTERECUPLKG NUMERIC(19, 3) NOT NULL,
    LAIZERECUEPL NUMERIC(19, 3) NOT NULL,
    PASSED INT4 NOT NULL,
    CONFORMITE INT4 NOT NULL,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE TESTFABRICINSPECTION (
    ID SERIAL NOT NULL,
    DATEDEBUT DATE,
    IDENTREETISSU INT4 NOT NULL,
    IDLISTEEMPLOYE INT4 NOT NULL,
    SENS INT4,
    NUMTISSU VARCHAR(90),
    IDSPEEDMACHINE INT4 NOT NULL,
    IDCHOIXQUALITE INT4 NOT NULL,
    LONGUEUR NUMERIC(19, 5) NOT NULL,
    PASSED INT4,
    GRAMMAGE NUMERIC(19, 3),
    TOLERANCE NUMERIC(19, 3),
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE LISTEEMPLOYE (
    ID SERIAL NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE SPEEDMACHINE (
    ID SERIAL NOT NULL,
    SPEED VARCHAR(90) NOT NULL,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE CHOIXQUALITE (
    ID SERIAL NOT NULL,
    CHOIX VARCHAR(50) NOT NULL,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE DEFAUTFABRICINSPECTION (
    IDQUALITEROULEAUTISSU INT4 NOT NULL,
    IDTESTFABRICINSPECTIONTISSU INT4 NOT NULL,
    IMAGE TEXT,
    METRAGE NUMERIC(19, 3),
    DEFAUT VARCHAR(200),
    DEFECTPOINT INT4,
    DEMERITPOINT INT4,
    SONNETTE VARCHAR(100) NOT NULL,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (IDQUALITEROULEAUTISSU, IDTESTFABRICINSPECTIONTISSU)
);

CREATE TABLE TESTRETRACTION (
    ID SERIAL NOT NULL,
    DATEDEBUT INT4,
    DATEPREPARATION INT4,
    DATEEVALUATION INT4,
    IDLISTEEMPLOYE INT4 NOT NULL,
    IDTYPELAVAGE INT4 NOT NULL,
    TEMPRELAXATION VARCHAR(10),
    OBSERVATION TEXT,
    PASSED INT4,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE TYPELAVAGE (
    ID SERIAL NOT NULL,
    TYPE VARCHAR(100) NOT NULL,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE QUALITEROULEAUTISSU_TESTRETRACTION (
    IDQUALITEROULEAUTISSU INT4 NOT NULL,
    IDTESTRETRACTION INT4 NOT NULL,
    LONGUEURELONG NUMERIC(19, 5) NOT NULL,
    LAIZEELONG NUMERIC(19, 4) NOT NULL,
    LONGUEUR NUMERIC(19, 5) NOT NULL,
    LAIZE NUMERIC(19, 4) NOT NULL,
    ECARTRETRAIT NUMERIC(19, 4) NOT NULL,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (IDQUALITEROULEAUTISSU, IDTESTRETRACTION)
);

CREATE TABLE TESTNUANCE (
    ID SERIAL NOT NULL,
    ENDROIT VARCHAR(90) NOT NULL,
    COMMENTAIRE TEXT NOT NULL,
    PASSED INT4 NOT NULL,
    NUANCE INT4 NOT NULL,
    ENVERS INT4 NOT NULL,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE QUALITEROULEAUTISSU_TESTNUANCE (
    IDQUALITEROULEAUTISSU INT4 NOT NULL,
    IDTESTNUANCE INT4 NOT NULL,
    IMAGE TEXT,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (IDQUALITEROULEAUTISSU, IDTESTNUANCE)
);

CREATE TABLE TESTDISCORGING (
    ID SERIAL NOT NULL,
    DATEDEBUT DATE NOT NULL,
    DATEPREPARATION DATE NOT NULL,
    DATEEVALUATION DATE NOT NULL,
    PASSED INT4 NOT NULL,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE QUALITEROULEAUTISSU_TESTDISCORGING (
    IDQUALITEROULEAUTISSU INT4 NOT NULL,
    IDTESTDISCORGING INT4 NOT NULL,
    TYPEFROTTEMENT INT4 NOT NULL,
    ECHELLEGRIS INT4 NOT NULL,
    DUREE INT4 NOT NULL,
    VALIDATIONTEST INT4 NOT NULL,
    REMARQUE TEXT,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (IDQUALITEROULEAUTISSU, IDTESTDISCORGING)
);

CREATE TABLE CODIFICATIONACCESSOIRE (
    ID SERIAL NOT NULL,
    CODE VARCHAR(90) NOT NULL,
    CHECKLIST VARCHAR(100) NOT NULL,
    GRAVITEDEFAULT VARCHAR(10) NOT NULL,
    FAMILLEACCESSOIREID INT4 NOT NULL,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE INSPECTIONACCESSOIRE (
    ID SERIAL NOT NULL,
    ENTREEACCESSOIREID INT4 NOT NULL,
    DATEDEBUT DATE NOT NULL,
    DATEFIN DATE NOT NULL,
    PACKTOTAL NUMERIC(19, 2) NOT NULL,
    AQL NUMERIC(19, 2) NOT NULL,
    POURCENTAGEINSPECT NUMERIC(19, 2) NOT NULL,
    PACKTOTALSELECT NUMERIC(19, 2) NOT NULL,
    TOTALDEFECT INT4 NOT NULL,
    MAJORDEFECT INT4 NOT NULL,
    MINORDEFECT INT4 NOT NULL,
    POURCENTAGEDEFECT NUMERIC(19, 2) NOT NULL,
    IMAGE TEXT,
    PASSED INT4 NOT NULL,
    CORRECTIVEACTION VARCHAR(150) NOT NULL,
    COMMENTAIRE TEXT,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE CODIFICATIONACCESSOIRE_INSPECTIONACCESSOIRE (
    IDCODIFICATIONACCESSOIRE INT4 NOT NULL,
    IDINSPECTIONACCESSOIRE INT4 NOT NULL,
    DEFECTQUANTITY INT4 NOT NULL,
    REMARQUE TEXT NOT NULL,
    ETAT INT4 DEFAULT 0 NOT NULL,
    PRIMARY KEY (IDCODIFICATIONACCESSOIRE, IDINSPECTIONACCESSOIRE)
);

CREATE VIEW V_ENTREE_TISSU AS
    SELECT
        CLASSEMATIEREPREMIERE.DESIGNATION         AS CLASSE,
        UTILISATIONWMS.UTILISATION,
        ENTREETISSU2.IDFAMILLETISSUS,
        ENTREETISSU2.DATEENTREE,
        ENTREETISSU2.DATEFACTURATION,
        ENTREETISSU2.IDCATEGORIETISSUS,
        ENTREETISSU2.IDCLASSEMATIEREPREMIERE,
        ENTREETISSU2.IDUTILISATIONWMS,
        ENTREETISSU2.IDDONNEBC,
        ENTREETISSU2.NUMEROBC,
        ENTREETISSU2.NUMEROBL,
        ENTREETISSU2.NUMEROFACTURE,
        ENTREETISSU2.IDFOURNISSEUR,
        ENTREETISSU2.IDCLIENT,
        ENTREETISSU2.MODELE,
        ENTREETISSU2.SAISON,
        ENTREETISSU2.DESIGNATION,
        ENTREETISSU2.REFTISSU,
        ENTREETISSU2.COMPOSITION,
        ENTREETISSU2.COULEUR,
        ENTREETISSU2.LAIZE,
        ENTREETISSU2.QTECOMMANDE,
        ENTREETISSU2.IDUNITEMESUREMATIEREPREMIERE,
        ENTREETISSU2.QTERECU,
        ENTREETISSU2.TAUXECART,
        ENTREETISSU2.NBROULEAU,
        ENTREETISSU2.NBLOT,
        ENTREETISSU2.PRIXUNITAIRE,
        ENTREETISSU2.IDUNITEMONETAIRE,
        ENTREETISSU2.RESTERECEVOIR,
        ENTREETISSU2.FRET,
        ENTREETISSU2.IMAGE,
        ENTREETISSU2.COMMENTAIRE,
        FAMILLETISSUS.FAMILLE_TISSUS
    FROM
        CLASSEMATIEREPREMIERE
        INNER JOIN ENTREETISSU AS ENTREETISSU2
        ON CLASSEMATIEREPREMIERE.ID = ENTREETISSU2.IDCLASSEMATIEREPREMIERE
        INNER JOIN UTILISATIONWMS
        ON ENTREETISSU2.IDUTILISATIONWMS = UTILISATIONWMS.ID
        INNER JOIN FAMILLETISSUS
        ON ENTREETISSU2.IDFAMILLETISSUS = FAMILLETISSUS.ID;

ALTER TABLE RACK
    ADD CONSTRAINT FKRACK155234 FOREIGN KEY (
        IDSECTIONWMS
    )
        REFERENCES SECTIONWMS (
            ID
        );

ALTER TABLE RACK
    ADD CONSTRAINT FKRACK421903 FOREIGN KEY (
        IDCATEGORIETISSU
    )
        REFERENCES CATEGORIETISSUS (
            ID
        );

ALTER TABLE CELLULE
    ADD CONSTRAINT FKCELLULE350976 FOREIGN KEY (
        IDRACK
    )
        REFERENCES RACK (
            ID
        );

ALTER TABLE CELLULE
    ADD CONSTRAINT FKCELLULE471252 FOREIGN KEY (
        IDCLASSEMATIEREPREMIERE
    )
        REFERENCES CLASSEMATIEREPREMIERE (
            ID
        );

ALTER TABLE CELLULE_ENTREETISSU
    ADD CONSTRAINT FKCELLULE_EN164995 FOREIGN KEY (
        IDENTREETISSU
    )
        REFERENCES ENTREETISSU (
            ID
        );

ALTER TABLE CELLULE_ENTREETISSU
    ADD CONSTRAINT FKCELLULE_EN653622 FOREIGN KEY (
        IDCELLULE
    )
        REFERENCES CELLULE (
            ID
        );

ALTER TABLE ENTREETISSU
    ADD CONSTRAINT FKENTREETISS722881 FOREIGN KEY (
        IDCATEGORIETISSUS
    )
        REFERENCES CATEGORIETISSUS (
            ID
        );

ALTER TABLE ENTREETISSU
    ADD CONSTRAINT FKENTREETISS950787 FOREIGN KEY (
        IDCLASSEMATIEREPREMIERE
    )
        REFERENCES CLASSEMATIEREPREMIERE (
            ID
        );

ALTER TABLE ENTREETISSU
    ADD CONSTRAINT FKENTREETISS105006 FOREIGN KEY (
        IDUTILISATIONWMS
    )
        REFERENCES UTILISATIONWMS (
            ID
        );

ALTER TABLE ENTREETISSU
    ADD CONSTRAINT FKENTREETISS542858 FOREIGN KEY (
        IDDONNEBC
    )
        REFERENCES DONNEBC (
            ID
        );

ALTER TABLE ENTREETISSU
    ADD CONSTRAINT FKENTREETISS680585 FOREIGN KEY (
        IDUNITEMESUREMATIEREPREMIERE
    )
        REFERENCES UNITEMESUREMATIEREPREMIERE (
            ID
        );

ALTER TABLE ENTREETISSU
    ADD CONSTRAINT FKENTREETISS812293 FOREIGN KEY (
        IDFOURNISSEUR
    )
        REFERENCES TIERS (
            ID
        );

ALTER TABLE ENTREETISSU
    ADD CONSTRAINT FKENTREETISS696993 FOREIGN KEY (
        IDCLIENT
    )
        REFERENCES TIERS (
            ID
        );

ALTER TABLE ENTREETISSU
    ADD CONSTRAINT FKENTREETISS771884 FOREIGN KEY (
        IDFAMILLETISSUS
    )
        REFERENCES FAMILLETISSUS (
            ID
        );

ALTER TABLE ENTREETISSU
    ADD CONSTRAINT FKENTREETISS587915 FOREIGN KEY (
        IDUNITEMONETAIRE
    )
        REFERENCES UNITEMONETAIRE (
            ID
        );

ALTER TABLE STOCKTISSU
    ADD CONSTRAINT FKSTOCKTISSU39980 FOREIGN KEY (
        IDCATEGORIETISSUS
    )
        REFERENCES CATEGORIETISSUS (
            ID
        );

ALTER TABLE STOCKTISSU
    ADD CONSTRAINT FKSTOCKTISSU257941 FOREIGN KEY (
        IDCLASSEMATIEREPREMIERE
    )
        REFERENCES CLASSEMATIEREPREMIERE (
            ID
        );

ALTER TABLE STOCKTISSU
    ADD CONSTRAINT FKSTOCKTISSU657855 FOREIGN KEY (
        IDUTILISATIONWMS
    )
        REFERENCES UTILISATIONWMS (
            ID
        );

ALTER TABLE STOCKTISSU
    ADD CONSTRAINT FKSTOCKTISSU396435 FOREIGN KEY (
        IDFOURNISSEUR
    )
        REFERENCES TIERS (
            ID
        );

ALTER TABLE STOCKTISSU_TIERS_MODELE
    ADD CONSTRAINT FKSTOCKTISSU771176 FOREIGN KEY (
        IDSTOCKTISSU
    )
        REFERENCES STOCKTISSU (
            ID
        );

ALTER TABLE STOCKTISSU_TIERS_MODELE
    ADD CONSTRAINT FKSTOCKTISSU154848 FOREIGN KEY (
        IDCLIENT
    )
        REFERENCES TIERS (
            ID
        );

ALTER TABLE RESERVATIONTISSU
    ADD CONSTRAINT FKRESERVATIO857639 FOREIGN KEY (
        IDSTOCKTISSU
    )
        REFERENCES STOCKTISSU (
            ID
        );

ALTER TABLE CELLULE_STOCKTISSU
    ADD CONSTRAINT FKCELLULE_ST164699 FOREIGN KEY (
        IDCELLULE
    )
        REFERENCES CELLULE (
            ID
        );

ALTER TABLE CELLULE_STOCKTISSU
    ADD CONSTRAINT FKCELLULE_ST648322 FOREIGN KEY (
        IDSTOCKTISSU
    )
        REFERENCES STOCKTISSU (
            ID
        );

ALTER TABLE STOCKTISSU
    ADD CONSTRAINT FKSTOCKTISSU436844 FOREIGN KEY (
        IDFAMILLETISSUS
    )
        REFERENCES FAMILLETISSUS (
            ID
        );

ALTER TABLE ENTREETISSU
    ADD CONSTRAINT FKENTREETISS313322 FOREIGN KEY (
        IDSTOCKTISSU
    )
        REFERENCES STOCKTISSU (
            ID
        );

ALTER TABLE SORTIETISSU
    ADD CONSTRAINT FKSORTIETISS616256 FOREIGN KEY (
        IDFAMILLETISSUS
    )
        REFERENCES FAMILLETISSUS (
            ID
        );

ALTER TABLE SORTIETISSU
    ADD CONSTRAINT FKSORTIETISS270127 FOREIGN KEY (
        IDSTOCKTISSU
    )
        REFERENCES STOCKTISSU (
            ID
        );

ALTER TABLE SORTIETISSU
    ADD CONSTRAINT FKSORTIETISS478443 FOREIGN KEY (
        IDUTILISATIONWMS
    )
        REFERENCES UTILISATIONWMS (
            ID
        );

ALTER TABLE SORTIETISSU
    ADD CONSTRAINT FKSORTIETISS68727 FOREIGN KEY (
        IDUNITEMESUREMATIEREPREMIERE
    )
        REFERENCES UNITEMESUREMATIEREPREMIERE (
            ID
        );

ALTER TABLE SORTIETISSU
    ADD CONSTRAINT FKSORTIETISS437353 FOREIGN KEY (
        IDCLASSEMATIEREPREMIERE
    )
        REFERENCES CLASSEMATIEREPREMIERE (
            ID
        );

ALTER TABLE SORTIETISSU
    ADD CONSTRAINT FKSORTIETISS860567 FOREIGN KEY (
        IDCATEGORIETISSUS
    )
        REFERENCES CATEGORIETISSUS (
            ID
        );

ALTER TABLE SORTIETISSU
    ADD CONSTRAINT FKSORTIETISS575847 FOREIGN KEY (
        IDFOURNISSEUR
    )
        REFERENCES TIERS (
            ID
        );

ALTER TABLE SORTIETISSU
    ADD CONSTRAINT FKSORTIETISS886455 FOREIGN KEY (
        IDCLIENT
    )
        REFERENCES TIERS (
            ID
        );

ALTER TABLE STOCKTISSU
    ADD CONSTRAINT FKSTOCKTISSU889314 FOREIGN KEY (
        IDUNITEMESUREMATIEREPREMIERE
    )
        REFERENCES UNITEMESUREMATIEREPREMIERE (
            ID
        );

ALTER TABLE RETOUR_TISSU
    ADD CONSTRAINT FKRETOUR_TIS971470 FOREIGN KEY (
        IDSORTIETISSU
    )
        REFERENCES SORTIETISSU (
            ID
        );

ALTER TABLE ENTREECONSOMMABLE
    ADD CONSTRAINT FKENTREECONS471414 FOREIGN KEY (
        IDFOURNISSEUR
    )
        REFERENCES TIERS (
            ID
        );

ALTER TABLE ENTREECONSOMMABLE
    ADD CONSTRAINT FKENTREECONS37873 FOREIGN KEY (
        IDCLIENT
    )
        REFERENCES TIERS (
            ID
        );

ALTER TABLE ENTREECONSOMMABLE
    ADD CONSTRAINT FKENTREECONS21465 FOREIGN KEY (
        IDUNITEMESUREMATIEREPREMIERE
    )
        REFERENCES UNITEMESUREMATIEREPREMIERE (
            ID
        );

ALTER TABLE ENTREECONSOMMABLE
    ADD CONSTRAINT FKENTREECONS928794 FOREIGN KEY (
        IDUNITEMONETAIRE
    )
        REFERENCES UNITEMONETAIRE (
            ID
        );

ALTER TABLE CELLULE_ENTREECONSOMMABLE
    ADD CONSTRAINT FKCELLULE_EN813771 FOREIGN KEY (
        IDCELLULE
    )
        REFERENCES CELLULE (
            ID
        );

ALTER TABLE CELLULE_ENTREECONSOMMABLE
    ADD CONSTRAINT FKCELLULE_EN401373 FOREIGN KEY (
        IDENTREECONSOMMABLE
    )
        REFERENCES ENTREECONSOMMABLE (
            ID
        );

ALTER TABLE STOCKCONSOMMABLE
    ADD CONSTRAINT FKSTOCKCONSO955082 FOREIGN KEY (
        IDFOURNISSEUR
    )
        REFERENCES TIERS (
            ID
        );

ALTER TABLE CLIENT_STOCKCONSOMMABLE
    ADD CONSTRAINT FKCLIENT_STO229160 FOREIGN KEY (
        IDCLIENT
    )
        REFERENCES TIERS (
            ID
        );

ALTER TABLE CLIENT_STOCKCONSOMMABLE
    ADD CONSTRAINT FKCLIENT_STO591196 FOREIGN KEY (
        IDSTOCKCONSOMMABLE
    )
        REFERENCES STOCKCONSOMMABLE (
            ID
        );

ALTER TABLE STOCKCONSOMMABLE
    ADD CONSTRAINT FKSTOCKCONSO422345 FOREIGN KEY (
        IDUNITEMESUREMATIEREPREMIERE
    )
        REFERENCES UNITEMESUREMATIEREPREMIERE (
            ID
        );

ALTER TABLE SOTIECONSOMMABLE
    ADD CONSTRAINT FKSOTIECONSO841583 FOREIGN KEY (
        IDCLIENT
    )
        REFERENCES TIERS (
            ID
        );

ALTER TABLE SOTIECONSOMMABLE
    ADD CONSTRAINT FKSOTIECONSO350871 FOREIGN KEY (
        IDFOURNISSEUR
    )
        REFERENCES TIERS (
            ID
        );

ALTER TABLE ENTREEACCESSOIRE
    ADD CONSTRAINT FKENTREEACCE829449 FOREIGN KEY (
        IDFOURNISSEUR
    )
        REFERENCES TIERS (
            ID
        );

ALTER TABLE ENTREEACCESSOIRE
    ADD CONSTRAINT FKENTREEACCE338737 FOREIGN KEY (
        IDCLIENT
    )
        REFERENCES TIERS (
            ID
        );

ALTER TABLE ENTREEACCESSOIRE
    ADD CONSTRAINT FKENTREEACCE840419 FOREIGN KEY (
        IDFAMILLEACCESSOIRE
    )
        REFERENCES FAMILLEACCESSOIRE (
            ID
        );

ALTER TABLE ENTREEACCESSOIRE
    ADD CONSTRAINT FKENTREEACCE309044 FOREIGN KEY (
        IDCLASSEMATIEREPREMIERE
    )
        REFERENCES CLASSEMATIEREPREMIERE (
            ID
        );

ALTER TABLE ENTREEACCESSOIRE
    ADD CONSTRAINT FKENTREEACCE322329 FOREIGN KEY (
        IDUNITEMESUREMATIEREPREMIERE
    )
        REFERENCES UNITEMESUREMATIEREPREMIERE (
            ID
        );

ALTER TABLE ENTREEACCESSOIRE
    ADD CONSTRAINT FKENTREEACCE229659 FOREIGN KEY (
        IDUNITEMONETAIRE
    )
        REFERENCES UNITEMONETAIRE (
            ID
        );

ALTER TABLE RETOURCONSOMMABLE
    ADD CONSTRAINT FKRETOURCONS505046 FOREIGN KEY (
        IDSOTIECONSOMMABLE
    )
        REFERENCES SOTIECONSOMMABLE (
            ID
        );

ALTER TABLE CELLULE_STOCKCONSOMMABLE
    ADD CONSTRAINT FKCELLULE_ST132698 FOREIGN KEY (
        IDCELLULE
    )
        REFERENCES CELLULE (
            ID
        );

ALTER TABLE CELLULE_STOCKCONSOMMABLE
    ADD CONSTRAINT FKCELLULE_ST627439 FOREIGN KEY (
        IDSTOCKCONSOMMABLE
    )
        REFERENCES STOCKCONSOMMABLE (
            ID
        );

ALTER TABLE ENTREEACCESSOIRE_CELLULE
    ADD CONSTRAINT FKENTREEACCE356170 FOREIGN KEY (
        IDENTREEACCESSOIRE
    )
        REFERENCES ENTREEACCESSOIRE (
            ID
        );

ALTER TABLE ENTREEACCESSOIRE_CELLULE
    ADD CONSTRAINT FKENTREEACCE620812 FOREIGN KEY (
        IDCELLULE
    )
        REFERENCES CELLULE (
            ID
        );

ALTER TABLE STOCKACCESSOIRE_CELLULE
    ADD CONSTRAINT FKSTOCKACCES770071 FOREIGN KEY (
        IDSTOCKACCESSOIRE
    )
        REFERENCES STOCKACCESSOIRE (
            ID
        );

ALTER TABLE STOCKACCESSOIRE_CELLULE
    ADD CONSTRAINT FKSTOCKACCES292498 FOREIGN KEY (
        IDCELLULE
    )
        REFERENCES CELLULE (
            ID
        );

ALTER TABLE STOCKACCESSOIRE
    ADD CONSTRAINT FKSTOCKACCES325106 FOREIGN KEY (
        IDFAMILLEACCESSOIRE
    )
        REFERENCES FAMILLEACCESSOIRE (
            ID
        );

ALTER TABLE STOCKACCESSOIRE
    ADD CONSTRAINT FKSTOCKACCES336076 FOREIGN KEY (
        IDFOURNISSEUR
    )
        REFERENCES TIERS (
            ID
        );

ALTER TABLE CLIENT_STOCKACCESSOIRE
    ADD CONSTRAINT FKCLIENT_STO349317 FOREIGN KEY (
        IDTIERS
    )
        REFERENCES TIERS (
            ID
        );

ALTER TABLE CLIENT_STOCKACCESSOIRE
    ADD CONSTRAINT FKCLIENT_STO497910 FOREIGN KEY (
        IDSTOCKACCESSOIRE
    )
        REFERENCES STOCKACCESSOIRE (
            ID
        );

ALTER TABLE STOCKACCESSOIRE
    ADD CONSTRAINT FKSTOCKACCES644206 FOREIGN KEY (
        CLASSEMATIEREPREMIEREID
    )
        REFERENCES CLASSEMATIEREPREMIERE (
            ID
        );

ALTER TABLE ENTREECONSOMMABLE
    ADD CONSTRAINT FKENTREECONS675836 FOREIGN KEY (
        IDSTOCKCONSOMMABLE
    )
        REFERENCES STOCKCONSOMMABLE (
            ID
        );

ALTER TABLE STOCKACCESSOIRE
    ADD CONSTRAINT FKSTOCKACCES808930 FOREIGN KEY (
        UNITEMESUREMATIEREPREMIEREID
    )
        REFERENCES UNITEMESUREMATIEREPREMIERE (
            ID
        );

ALTER TABLE SOTIECONSOMMABLE
    ADD CONSTRAINT FKSOTIECONSO857991 FOREIGN KEY (
        IDUNITEMESUREMATIEREPREMIERE
    )
        REFERENCES UNITEMESUREMATIEREPREMIERE (
            ID
        );

ALTER TABLE SORTIEACCESSOIRE
    ADD CONSTRAINT FKSORTIEACCE158085 FOREIGN KEY (
        IDFAMILLEACCESSOIRE
    )
        REFERENCES FAMILLEACCESSOIRE (
            ID
        );

ALTER TABLE SORTIEACCESSOIRE
    ADD CONSTRAINT FKSORTIEACCE147115 FOREIGN KEY (
        IDFOURNISSEUR
    )
        REFERENCES TIERS (
            ID
        );

ALTER TABLE SORTIEACCESSOIRE
    ADD CONSTRAINT FKSORTIEACCE656402 FOREIGN KEY (
        IDCLIENT
    )
        REFERENCES TIERS (
            ID
        );

ALTER TABLE SORTIEACCESSOIRE
    ADD CONSTRAINT FKSORTIEACCE8621 FOREIGN KEY (
        IDCLASSEMATIEREPREMIERE
    )
        REFERENCES CLASSEMATIEREPREMIERE (
            ID
        );

ALTER TABLE RETOURACCESSOIRE
    ADD CONSTRAINT FKRETOURACCE395452 FOREIGN KEY (
        IDSORTIEACCESSOIRE
    )
        REFERENCES SORTIEACCESSOIRE (
            ID
        );

ALTER TABLE FAMILLEWMS
    ADD CONSTRAINT FKFAMILLEWMS556646 FOREIGN KEY (
        IDWMS_TYPE
    )
        REFERENCES WMS_TYPE (
            ID
        );

ALTER TABLE ENTREEWMS
    ADD CONSTRAINT FKENTREEWMS637281 FOREIGN KEY (
        IDCLIENT
    )
        REFERENCES TIERS (
            ID
        );

ALTER TABLE ENTREEWMS
    ADD CONSTRAINT FKENTREEWMS364062 FOREIGN KEY (
        IDFAMILLEWMS
    )
        REFERENCES FAMILLEWMS (
            ID
        );

ALTER TABLE ENTREEWMS
    ADD CONSTRAINT FKENTREEWMS146569 FOREIGN KEY (
        IDFOURNISSEUR
    )
        REFERENCES TIERS (
            ID
        );

ALTER TABLE ENTREEWMS
    ADD CONSTRAINT FKENTREEWMS285063 FOREIGN KEY (
        IDCLASSEMATIEREPREMIERE
    )
        REFERENCES CLASSEMATIEREPREMIERE (
            ID
        );

ALTER TABLE ENTREEWMS
    ADD CONSTRAINT FKENTREEWMS653689 FOREIGN KEY (
        IDUNITEMESUREMATIEREPREMIERE
    )
        REFERENCES UNITEMESUREMATIEREPREMIERE (
            ID
        );

ALTER TABLE ENTREEWMS
    ADD CONSTRAINT FKENTREEWMS746359 FOREIGN KEY (
        IDUNITEMONETAIRE
    )
        REFERENCES UNITEMONETAIRE (
            ID
        );

ALTER TABLE STOCKWMS
    ADD CONSTRAINT FKSTOCKWMS149368 FOREIGN KEY (
        IDCLIENT
    )
        REFERENCES TIERS (
            ID
        );

ALTER TABLE STOCKWMS
    ADD CONSTRAINT FKSTOCKWMS658655 FOREIGN KEY (
        IDFOURNISSEUR
    )
        REFERENCES TIERS (
            ID
        );

ALTER TABLE STOCKWMS
    ADD CONSTRAINT FKSTOCKWMS876148 FOREIGN KEY (
        IDFAMILLEWMS
    )
        REFERENCES FAMILLEWMS (
            ID
        );

ALTER TABLE STOCKWMS
    ADD CONSTRAINT FKSTOCKWMS174441 FOREIGN KEY (
        IDCLASSEMATIEREPREMIERE
    )
        REFERENCES CLASSEMATIEREPREMIERE (
            ID
        );

ALTER TABLE STOCKWMS
    ADD CONSTRAINT FKSTOCKWMS165776 FOREIGN KEY (
        IDUNITEMESUREMATIEREPREMIERE
    )
        REFERENCES UNITEMESUREMATIEREPREMIERE (
            ID
        );

ALTER TABLE ENTREEWMS
    ADD CONSTRAINT FKENTREEWMS705880 FOREIGN KEY (
        STOCKWMSID
    )
        REFERENCES STOCKWMS (
            ID
        );

ALTER TABLE ENTREEWMS_CELLULE
    ADD CONSTRAINT FKENTREEWMS_331296 FOREIGN KEY (
        IDENTREEWMS
    )
        REFERENCES ENTREEWMS (
            ID
        );

ALTER TABLE ENTREEWMS_CELLULE
    ADD CONSTRAINT FKENTREEWMS_871429 FOREIGN KEY (
        IDCELLULE
    )
        REFERENCES CELLULE (
            ID
        );

ALTER TABLE STOCKWMS_CELLULE
    ADD CONSTRAINT FKSTOCKWMS_C50918 FOREIGN KEY (
        IDSTOCKWMS
    )
        REFERENCES STOCKWMS (
            ID
        );

ALTER TABLE STOCKWMS_CELLULE
    ADD CONSTRAINT FKSTOCKWMS_C427619 FOREIGN KEY (
        IDCELLULE
    )
        REFERENCES CELLULE (
            ID
        );

ALTER TABLE CLIENT_STOCKWMS
    ADD CONSTRAINT FKCLIENT_STO293362 FOREIGN KEY (
        IDCLIENT
    )
        REFERENCES TIERS (
            ID
        );

ALTER TABLE CLIENT_STOCKWMS
    ADD CONSTRAINT FKCLIENT_STO947529 FOREIGN KEY (
        IDSTOCKWMS
    )
        REFERENCES STOCKWMS (
            ID
        );

ALTER TABLE SORTIEWMS
    ADD CONSTRAINT FKSORTIEWMS56326 FOREIGN KEY (
        FAMILLEWMSID
    )
        REFERENCES FAMILLEWMS (
            ID
        );

ALTER TABLE SORTIEWMS
    ADD CONSTRAINT FKSORTIEWMS135543 FOREIGN KEY (
        IDCLIENT
    )
        REFERENCES TIERS (
            ID
        );

ALTER TABLE SORTIEWMS
    ADD CONSTRAINT FKSORTIEWMS626255 FOREIGN KEY (
        IDFOURNISSEUR
    )
        REFERENCES TIERS (
            ID
        );

ALTER TABLE SORTIEWMS
    ADD CONSTRAINT FKSORTIEWMS512238 FOREIGN KEY (
        IDCLASSEMATIEREPREMIERE
    )
        REFERENCES CLASSEMATIEREPREMIERE (
            ID
        );

ALTER TABLE QUALITEROULEAUTISSU
    ADD CONSTRAINT FKQUALITEROU252522 FOREIGN KEY (
        IDENTREETISSU
    )
        REFERENCES ENTREETISSU (
            ID
        );

ALTER TABLE TESTCONFORMITETISSU
    ADD CONSTRAINT FKTESTCONFOR318012 FOREIGN KEY (
        IDENTREETISSU
    )
        REFERENCES ENTREETISSU (
            ID
        );

ALTER TABLE TESTFABRICINSPECTION
    ADD CONSTRAINT FKTESTFABRIC269709 FOREIGN KEY (
        IDENTREETISSU
    )
        REFERENCES ENTREETISSU (
            ID
        );

ALTER TABLE TESTFABRICINSPECTION
    ADD CONSTRAINT FKTESTFABRIC844661 FOREIGN KEY (
        IDLISTEEMPLOYE
    )
        REFERENCES LISTEEMPLOYE (
            ID
        );

ALTER TABLE TESTFABRICINSPECTION
    ADD CONSTRAINT FKTESTFABRIC469422 FOREIGN KEY (
        IDSPEEDMACHINE
    )
        REFERENCES SPEEDMACHINE (
            ID
        );

ALTER TABLE TESTFABRICINSPECTION
    ADD CONSTRAINT FKTESTFABRIC55776 FOREIGN KEY (
        IDCHOIXQUALITE
    )
        REFERENCES CHOIXQUALITE (
            ID
        );

ALTER TABLE DEFAUTFABRICINSPECTION
    ADD CONSTRAINT FKDEFAUTFABR310248 FOREIGN KEY (
        IDQUALITEROULEAUTISSU
    )
        REFERENCES QUALITEROULEAUTISSU (
            ID
        );

ALTER TABLE DEFAUTFABRICINSPECTION
    ADD CONSTRAINT FKDEFAUTFABR169134 FOREIGN KEY (
        IDTESTFABRICINSPECTIONTISSU
    )
        REFERENCES TESTFABRICINSPECTION (
            ID
        );

ALTER TABLE TESTRETRACTION
    ADD CONSTRAINT FKTESTRETRAC279978 FOREIGN KEY (
        IDLISTEEMPLOYE
    )
        REFERENCES LISTEEMPLOYE (
            ID
        );

ALTER TABLE TESTRETRACTION
    ADD CONSTRAINT FKTESTRETRAC103328 FOREIGN KEY (
        IDTYPELAVAGE
    )
        REFERENCES TYPELAVAGE (
            ID
        );

ALTER TABLE QUALITEROULEAUTISSU_TESTRETRACTION
    ADD CONSTRAINT FKQUALITEROU773614 FOREIGN KEY (
        IDQUALITEROULEAUTISSU
    )
        REFERENCES QUALITEROULEAUTISSU (
            ID
        );

ALTER TABLE QUALITEROULEAUTISSU_TESTRETRACTION
    ADD CONSTRAINT FKQUALITEROU506494 FOREIGN KEY (
        IDTESTRETRACTION
    )
        REFERENCES TESTRETRACTION (
            ID
        );

ALTER TABLE QUALITEROULEAUTISSU_TESTNUANCE
    ADD CONSTRAINT FKQUALITEROU536316 FOREIGN KEY (
        IDQUALITEROULEAUTISSU
    )
        REFERENCES QUALITEROULEAUTISSU (
            ID
        );

ALTER TABLE QUALITEROULEAUTISSU_TESTNUANCE
    ADD CONSTRAINT FKQUALITEROU780447 FOREIGN KEY (
        IDTESTNUANCE
    )
        REFERENCES TESTNUANCE (
            ID
        );

ALTER TABLE QUALITEROULEAUTISSU_TESTDISCORGING
    ADD CONSTRAINT FKQUALITEROU344496 FOREIGN KEY (
        IDQUALITEROULEAUTISSU
    )
        REFERENCES QUALITEROULEAUTISSU (
            ID
        );

ALTER TABLE QUALITEROULEAUTISSU_TESTDISCORGING
    ADD CONSTRAINT FKQUALITEROU917645 FOREIGN KEY (
        IDTESTDISCORGING
    )
        REFERENCES TESTDISCORGING (
            ID
        );

ALTER TABLE CODIFICATIONACCESSOIRE
    ADD CONSTRAINT FKCODIFICATI806648 FOREIGN KEY (
        FAMILLEACCESSOIREID
    )
        REFERENCES FAMILLEACCESSOIRE (
            ID
        );

ALTER TABLE INSPECTIONACCESSOIRE
    ADD CONSTRAINT FKINSPECTION396342 FOREIGN KEY (
        ENTREEACCESSOIREID
    )
        REFERENCES ENTREEACCESSOIRE (
            ID
        );

ALTER TABLE CODIFICATIONACCESSOIRE_INSPECTIONACCESSOIRE
    ADD CONSTRAINT FKCODIFICATI281142 FOREIGN KEY (
        IDCODIFICATIONACCESSOIRE
    )
        REFERENCES CODIFICATIONACCESSOIRE (
            ID
        );

ALTER TABLE CODIFICATIONACCESSOIRE_INSPECTIONACCESSOIRE
    ADD CONSTRAINT FKCODIFICATI121217 FOREIGN KEY (
        IDINSPECTIONACCESSOIRE
    )
        REFERENCES INSPECTIONACCESSOIRE (
            ID
        );
