<?php

namespace App\Models\MES;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class VGeneralFinalRecap extends Model
{
    use HasFactory;

    protected $table = 'v_general_final_recap';
    public $timestamps = false;
    protected $primaryKey = 'id';
    protected $fillable = [
        'id',
        'date_entree',
        'date_livraison',
        'nom_modele',
        'theme',
        'qte_commande_provisoire',
        'taille_base',
        'requete_client',
        'commentaire_merch',
        'photo_commande',
        'etat',
        'id_unite_taille_min',
        'id_unite_taille_max',
        'nomtier',
        'id_tiers',
        'nom_style',
        'id_style',
        'type_incontern',
        'id_incontern',
        'type_phase',
        'id_phase',
        'type_saison',
        'id_saison',
        'tailleMin',
        'tailleMax',
        'type_stade',
        'id_stade',
        'type_etat',
        'periode',
        'id_periode',
        'id_etat',
        'smv_prod',
        'smv_finition',
        'prix_print',
        'nombre_points',
        'smv_brod_main',
        'recapcommande_id',
        'etdrevise',
        'etdpropose',
        'receptionbc',
        'bcclient',
        'date_bc_tissu',
        'date_bc_access',
        'recap_etat',
        'destination_id',
        'numerocommande',
        'etdinitial',
        'datelivraisonexacte',
        'dateinspection',
        'qteof',
        'deststd_id',
        'designation',
        'deststd_etat',
        'micro_resultat_id',
        'micro_id_etape',
        'micro_datecalcul',
        'micro_etape_nbjour',
        'micro_realisation',
        'micro_semaine',
        'micro_commentaires',
        'micro_etat',
        'tissus_detailbc_id',
        'tissus_id_bc',
        'tissus_etat',
        'tissus_dateconfirmation',
        'tissus_date_bc',
        'tissus_numero_bc',
        'tissus_id_type_bc',
        'tissus_idtier',
        'tissus_echeance',
        'tissus_bc_etat',
        'accy_detailbc_id',
        'accy_id_bc',
        'accy_etat',
        'accy_dateconfirmation',
        'accy_date_bc',
        'accy_numero_bc',
        'accy_id_type_bc',
        'accy_idtier',
        'accy_echeance',
        'accy_bc_etat',
        'max_datearrivereelle',
        'combined_final_deadline',
        'combined_final_deadline_accy',
        'accy_max_datearrivereelle',
        'livraison_couleur',
        'id_demande_client',
        'types_lavage',
        'types_valeur_ajout'
    ];
}
																											